package me.meetmywagon23.dragonshoardwa.datagen;

import me.meetmywagon23.dragonshoardwa.registries.ItemGroupRegistry;
import me.meetmywagon23.dragonshoardwa.registries.ItemsRegistry;
import me.meetmywagon23.dragonshoardwa.registries.ToolsRegistry;
import me.meetmywagon23.dragonshoardwa.registries.WeaponsRegistry;
import net.fabricmc.fabric.api.datagen.v1.FabricDataOutput;
import net.fabricmc.fabric.api.datagen.v1.provider.FabricLanguageProvider;

public class DragonsHoardWAEnglishUSLangProvider extends FabricLanguageProvider {
    protected DragonsHoardWAEnglishUSLangProvider(FabricDataOutput dataOutput) {
        super(dataOutput, "en_us");
    }

    @Override
    public void generateTranslations(TranslationBuilder translationBuilder) {
        translationBuilder.add(ItemGroupRegistry.DRAGONSHOARD_WA, "Dragon's Hoard: Weapons and Armors");

        translationBuilder.add(ItemsRegistry.COPPER_COIN, "Copper Coin");
        translationBuilder.add(ItemsRegistry.COPPER_COIN_FIVE_STACK, "Copper Coin Stack (5)");
        translationBuilder.add(ItemsRegistry.COPPER_COIN_TEN_STACK, "Copper Coin Stack (10)");
        translationBuilder.add(ItemsRegistry.SILVER_COIN, "Silver Coin");
        translationBuilder.add(ItemsRegistry.SILVER_COIN_FIVE_STACK, "Silver Coin Stack (5)");
        translationBuilder.add(ItemsRegistry.SILVER_COIN_TEN_STACK, "Silver Coin Stack (10)");
        translationBuilder.add(ItemsRegistry.GOLD_COIN, "Golden Coin");
        translationBuilder.add(ItemsRegistry.GOLD_COIN_FIVE_STACK, "Golden Coin Stack (5)");
        translationBuilder.add(ItemsRegistry.GOLD_COIN_TEN_STACK, "Golden Coin Stack (10)");
        translationBuilder.add(ItemsRegistry.PLATINUM_COIN, "Platinum Coin");
        translationBuilder.add(ItemsRegistry.PLATINUM_COIN_FIVE_STACK, "Platinum Coin Stack (5)");
        translationBuilder.add(ItemsRegistry.PLATINUM_COIN_TEN_STACK, "Platinum Coin Stack (10)");

        translationBuilder.add(ItemsRegistry.LIGHT_ARMOR_MESH, "Light Armor Mesh");
        translationBuilder.add(ItemsRegistry.WITHER_BONE, "Wither Bone");
        translationBuilder.add(ItemsRegistry.BONE_BLIGHT, "Bone Blight");
        translationBuilder.add(ItemsRegistry.SKELETON_RIBCAGE, "Skeleton Ribcage");
        translationBuilder.add(ItemsRegistry.WITHER_SKELETON_RIBCAGE, "Wither Skeleton Ribcage");
        translationBuilder.add(ItemsRegistry.SKELETON_PELVIS, "Skeleton Pelvis");
        translationBuilder.add(ItemsRegistry.WITHER_SKELETON_PELVIS, "Wither Skeleton Pelvis");
        translationBuilder.add(ItemsRegistry.DRAGON_SCALE, "Dragon Scale");
        translationBuilder.add(ItemsRegistry.DRAGON_BONE, "Dragon Bone");
        translationBuilder.add(ItemsRegistry.DIVINE_CATALYST, "Divine Catalyst");
        translationBuilder.add(ItemsRegistry.ANCIENT_ICE, "Ancient Ice");

        translationBuilder.add(ItemsRegistry.RAW_ADAMANT_FRAGMENT, "Raw Adamant Fragment");
        translationBuilder.add(ItemsRegistry.ADAMANTINE_NUGGET, "Adamantine Nugget");
        translationBuilder.add(ItemsRegistry.ADAMANTINE_INGOT, "Adamantine Ingot");
        translationBuilder.add(ItemsRegistry.ADAMANTINE_COATED_DRAGON_BONE, "Adamantine Coated Dragon Bone");
        translationBuilder.add(ItemsRegistry.ADAMANTINE_COATED_DRAGON_SCALE, "Adamantine Coated Dragon Scale");
        translationBuilder.add(ItemsRegistry.PRISTINE_ADAMANTINE_COATED_DRAGON_BONE, "Pristine Adamantine Coated Dragon Bone");
        translationBuilder.add(ItemsRegistry.PRISTINE_ADAMANTINE_COATED_DRAGON_SCALE, "Pristine Adamantine Coated Dragon Scale");
        translationBuilder.add(ItemsRegistry.RAW_ALUMINUM, "Raw Aluminum");
        translationBuilder.add(ItemsRegistry.ALUMINUM_NUGGET, "Aluminum Nugget");
        translationBuilder.add(ItemsRegistry.ALUMINUM_INGOT, "Aluminum Ingot");
        //translationBuilder.add(ItemsRegistry.RAW_BRASS, "Raw Brass");
        //translationBuilder.add(ItemsRegistry.BRASS_NUGGET, "Brass Nugget");
        //translationBuilder.add(ItemsRegistry.BRASS_INGOT, "Brass Ingot");
        translationBuilder.add(ItemsRegistry.RAW_BRONZE, "Raw Bronze");
        translationBuilder.add(ItemsRegistry.BRONZE_NUGGET, "Bronze Nugget");
        translationBuilder.add(ItemsRegistry.BRONZE_INGOT, "Bronze Ingot");
        translationBuilder.add(ItemsRegistry.RAW_COLD_IRON, "Raw Cold Iron");
        translationBuilder.add(ItemsRegistry.COLD_IRON_NUGGET, "Cold Iron Nugget");
        translationBuilder.add(ItemsRegistry.COLD_IRON_INGOT, "Cold Iron Ingot");
        translationBuilder.add(ItemsRegistry.COPPER_NUGGET, "Copper Nugget");
        translationBuilder.add(ItemsRegistry.DARK_STEEL_NUGGET, "Dark Steel Nugget");
        translationBuilder.add(ItemsRegistry.DARK_STEEL_INGOT, "Dark Steel Ingot");
        translationBuilder.add(ItemsRegistry.RAW_ELECTRUM, "Raw Electrum");
        translationBuilder.add(ItemsRegistry.ELECTRUM_NUGGET, "Electrum Nugget");
        translationBuilder.add(ItemsRegistry.ELECTRUM_INGOT, "Electrum Ingot");
        translationBuilder.add(ItemsRegistry.RAW_ELVEN_STEEL, "Raw Elven Steel");
        translationBuilder.add(ItemsRegistry.ELVEN_STEEL_NUGGET, "Elven Steel Nugget");
        translationBuilder.add(ItemsRegistry.ELVEN_STEEL_INGOT, "Elven Steel Ingot");
        translationBuilder.add(ItemsRegistry.RAW_INFERNAL_IRON, "Raw Infernal Iron");
        translationBuilder.add(ItemsRegistry.RAW_INFERNAL_SLIVER, "Raw Infernal Sliver");
        translationBuilder.add(ItemsRegistry.INFERNAL_IRON_NUGGET, "Infernal Iron Nugget");
        translationBuilder.add(ItemsRegistry.INFERNAL_IRON_INGOT, "Infernal Iron Ingot");
        translationBuilder.add(ItemsRegistry.RAW_ITANIUM, "Raw Itanium");
        translationBuilder.add(ItemsRegistry.ITANIUM_NUGGET, "Itanium Nugget");
        translationBuilder.add(ItemsRegistry.ITANIUM_INGOT, "Itanium Ingot");
        translationBuilder.add(ItemsRegistry.RAW_LEAD, "Raw Lead");
        translationBuilder.add(ItemsRegistry.LEAD_NUGGET, "Lead Nugget");
        translationBuilder.add(ItemsRegistry.LEAD_INGOT, "Lead Ingot");
        translationBuilder.add(ItemsRegistry.RAW_MITHRIL, "Raw Mithril");
        translationBuilder.add(ItemsRegistry.MITHRIL_NUGGET, "Mithril Nugget");
        translationBuilder.add(ItemsRegistry.MITHRIL_INGOT, "Mithril Ingot");
        translationBuilder.add(ItemsRegistry.RAW_NICKEL_ZINC, "Raw Nickel-Zinc");
        translationBuilder.add(ItemsRegistry.NICKEL_ZINC_NUGGET, "Nickel-Zinc Nugget");
        translationBuilder.add(ItemsRegistry.NICKEL_ZINC_INGOT, "Nickel-Zinc Ingot");
        translationBuilder.add(ItemsRegistry.RAW_PALLADIUM, "Raw Palladium");
        translationBuilder.add(ItemsRegistry.PALLADIUM_NUGGET, "Palladium Nugget");
        translationBuilder.add(ItemsRegistry.PALLADIUM_INGOT, "Palladium Ingot");
        translationBuilder.add(ItemsRegistry.RAW_PLATINUM, "Raw Platinum");
        translationBuilder.add(ItemsRegistry.PLATINUM_NUGGET, "Platinum Nugget");
        translationBuilder.add(ItemsRegistry.PLATINUM_INGOT, "Platinum Ingot");
        translationBuilder.add(ItemsRegistry.PURE_CARBON, "Pure Carbon");
        translationBuilder.add(ItemsRegistry.RAW_SHADOW_ADAMANT, "Raw Shadow Adamant");
        translationBuilder.add(ItemsRegistry.SHADOW_ADAMANTINE_NUGGET, "Shadow Adamantine Nugget");
        translationBuilder.add(ItemsRegistry.SHADOW_ADAMANTINE_INGOT, "Shadow Adamantine Ingot");
        translationBuilder.add(ItemsRegistry.SHADOW_ADAMANTINE_COATED_DRAGON_BONE, "Shadow Adamantine Coated Dragon Bone");
        translationBuilder.add(ItemsRegistry.SHADOW_ADAMANTINE_COATED_DRAGON_SCALE, "Shadow Adamantine Coated Dragon Scale");
        translationBuilder.add(ItemsRegistry.PRISTINE_SHADOW_ADAMANTINE_COATED_DRAGON_BONE, "Pristine Shadow Adamantine Coated Dragon Bone");
        translationBuilder.add(ItemsRegistry.PRISTINE_SHADOW_ADAMANTINE_COATED_DRAGON_SCALE, "Pristine Shadow Adamantine Coated Dragon Scale");
        translationBuilder.add(ItemsRegistry.RAW_SILVER, "Raw Silver");
        translationBuilder.add(ItemsRegistry.SILVER_NUGGET, "Silver Nugget");
        translationBuilder.add(ItemsRegistry.SILVER_INGOT, "Silver Ingot");
        translationBuilder.add(ItemsRegistry.RAW_STARFALL_ORE, "Raw Starfall Ore");
        translationBuilder.add(ItemsRegistry.RAW_STEEL, "Raw Steel");
        translationBuilder.add(ItemsRegistry.STEEL_NUGGET, "Steel Nugget");
        translationBuilder.add(ItemsRegistry.STEEL_INGOT, "Steel Ingot");
        translationBuilder.add(ItemsRegistry.RAW_TIN, "Raw Tin");
        translationBuilder.add(ItemsRegistry.TIN_NUGGET, "Tin Nugget");
        translationBuilder.add(ItemsRegistry.TIN_INGOT, "Tin Ingot");
        translationBuilder.add(ItemsRegistry.RAW_TITANIUM, "Raw Titanium");
        translationBuilder.add(ItemsRegistry.TITANIUM_NUGGET, "Titanium Nugget");
        translationBuilder.add(ItemsRegistry.TITANIUM_INGOT, "Titanium Ingot");
        translationBuilder.add(ItemsRegistry.RAW_TUNGSTEN, "Raw Tungsten");
        translationBuilder.add(ItemsRegistry.TUNGSTEN_CARBIDE_NUGGET, "Tungsten Carbide Nugget");
        translationBuilder.add(ItemsRegistry.TUNGSTEN_CARBIDE_INGOT, "Tungsten Carbide Ingot");
        translationBuilder.add(ItemsRegistry.RAW_ZINC, "Raw Zinc");
        translationBuilder.add(ItemsRegistry.ZINC_NUGGET, "Zinc Nugget");
        translationBuilder.add(ItemsRegistry.ZINC_INGOT, "Zinc Ingot");

        translationBuilder.add(ItemsRegistry.ADAMANT_DUST, "Adamant Dust");
        translationBuilder.add(ItemsRegistry.ADAMANTINE_DUST, "Adamantine Dust");
        translationBuilder.add(ItemsRegistry.ALUMINUM_DUST, "Aluminum Dust");
        translationBuilder.add(ItemsRegistry.ARANDUR_DUST, "Arandur Dust");
        //translationBuilder.add(ItemsRegistry.BRASS_DUST, "Brass Dust");
        translationBuilder.add(ItemsRegistry.BRONZE_DUST, "Bronze Dust");
        translationBuilder.add(ItemsRegistry.COAL_DUST, "Coal Dust");
        translationBuilder.add(ItemsRegistry.COLD_IRON_DUST, "Cold Iron Dust");
        translationBuilder.add(ItemsRegistry.COPPER_DUST, "Copper Dust");
        translationBuilder.add(ItemsRegistry.DARK_STEEL_DUST, "Dark Steel Dust");
        translationBuilder.add(ItemsRegistry.DIAMOND_DUST, "Diamond Dust");
        translationBuilder.add(ItemsRegistry.ELECTRUM_DUST, "Electrum Dust");
        translationBuilder.add(ItemsRegistry.ELVEN_STEEL_DUST, "Elven Steel Dust");
        translationBuilder.add(ItemsRegistry.GLACIAL_DUST, "Glacial Dust");
        translationBuilder.add(ItemsRegistry.GOLD_DUST, "Golden Dust");
        translationBuilder.add(ItemsRegistry.INFERNAL_IRON_DUST, "Infernal Iron Dust");
        translationBuilder.add(ItemsRegistry.IRON_DUST, "Iron Dust");
        translationBuilder.add(ItemsRegistry.ITANIUM_DUST, "Itanium Dust");
        translationBuilder.add(ItemsRegistry.LEAD_DUST, "Lead Dust");
        translationBuilder.add(ItemsRegistry.MITHRIL_DUST, "Mithril Dust");
        translationBuilder.add(ItemsRegistry.NETHERITE_DUST, "Netherite Dust");
        translationBuilder.add(ItemsRegistry.NICKEL_DUST, "Nickel Dust");
        translationBuilder.add(ItemsRegistry.PALLADIUM_DUST, "Palladium Dust");
        translationBuilder.add(ItemsRegistry.PLATINUM_DUST, "Platinum Dust");
        translationBuilder.add(ItemsRegistry.SHADOW_ADAMANTINE_DUST, "Shadow Adamantine Dust");
        translationBuilder.add(ItemsRegistry.SILVER_DUST, "Silver Dust");
        translationBuilder.add(ItemsRegistry.STARFALL_DUST, "Starfall Dust");
        translationBuilder.add(ItemsRegistry.STEEL_DUST, "Steel Dust");
        translationBuilder.add(ItemsRegistry.TIN_DUST, "Tin Dust");
        translationBuilder.add(ItemsRegistry.TITANIUM_DUST, "Titanium Dust");
        translationBuilder.add(ItemsRegistry.TUNGSTEN_DUST, "Tungsten Dust");
        translationBuilder.add(ItemsRegistry.ZINC_DUST, "Zinc Dust");

        translationBuilder.add(ToolsRegistry.ADAMANTINE_PICKAXE, "Adamantine Pickaxe");
        translationBuilder.add(ToolsRegistry.ADAMANTINE_AXE, "Adamantine Axe");
        translationBuilder.add(ToolsRegistry.ADAMANTINE_SHOVEL, "Adamantine Shovel");
        translationBuilder.add(ToolsRegistry.ADAMANTINE_HOE, "Adamantine Hoe");
        translationBuilder.add(WeaponsRegistry.ADAMANTINE_BATTLEAXE, "Adamantine Battleaxe");
        // translationBuilder.add(WeaponsRegistry.ADAMANTINE_CAESTUS, "Adamantine Caestus");
        translationBuilder.add(WeaponsRegistry.ADAMANTINE_CLAYMORE, "Adamantine Claymore");
        translationBuilder.add(WeaponsRegistry.ADAMANTINE_DAGGER, "Adamantine Dagger");
        translationBuilder.add(WeaponsRegistry.ADAMANTINE_FALCHION, "Adamantine Falchion");
        translationBuilder.add(WeaponsRegistry.ADAMANTINE_GAUNTLET, "Adamantine Gauntlet");
        translationBuilder.add(WeaponsRegistry.ADAMANTINE_GLAIVE, "Adamantine Glaive");
        translationBuilder.add(WeaponsRegistry.ADAMANTINE_GREATSWORD, "Adamantine Greatsword");
        translationBuilder.add(WeaponsRegistry.ADAMANTINE_HALBERD, "Adamantine Halberd");
        translationBuilder.add(WeaponsRegistry.ADAMANTINE_HANDAXE, "Adamantine Handaxe");
        translationBuilder.add(WeaponsRegistry.ADAMANTINE_LONG_SPEAR, "Adamantine LONG_SPEAR");
        translationBuilder.add(WeaponsRegistry.ADAMANTINE_LONGSWORD, "Adamantine Longsword");
        translationBuilder.add(WeaponsRegistry.ADAMANTINE_MACE, "Adamantine Mace");
        translationBuilder.add(WeaponsRegistry.ADAMANTINE_PIKE, "Adamantine Pike");
        translationBuilder.add(WeaponsRegistry.ADAMANTINE_QUARTERSTAFF, "Adamantine Quarterstaff");
        translationBuilder.add(WeaponsRegistry.ADAMANTINE_RAPIER, "Adamantine Rapier");
        translationBuilder.add(WeaponsRegistry.ADAMANTINE_SCIMITAR, "Adamantine Scimitar");
        translationBuilder.add(WeaponsRegistry.ADAMANTINE_SCYTHE, "Adamantine Scythe");
        translationBuilder.add(WeaponsRegistry.ADAMANTINE_SICKLE, "Adamantine Sickle");
        translationBuilder.add(WeaponsRegistry.ADAMANTINE_SPEAR, "Adamantine Spear");
        translationBuilder.add(WeaponsRegistry.ADAMANTINE_SWORD, "Adamantine Sword");
        translationBuilder.add(WeaponsRegistry.ADAMANTINE_TRIDENT, "Adamantine Trident");
        translationBuilder.add(WeaponsRegistry.ADAMANTINE_WARHAMMER, "Adamantine War Hammer");

        translationBuilder.add(ToolsRegistry.ADAMANTINE_DRAGON_BONE_PICKAXE, "Adamantine Dragon Bone Pickaxe");
        translationBuilder.add(ToolsRegistry.ADAMANTINE_DRAGON_BONE_AXE, "Adamantine Dragon Bone Axe");
        translationBuilder.add(ToolsRegistry.ADAMANTINE_DRAGON_BONE_SHOVEL, "Adamantine Dragon Bone Shovel");
        translationBuilder.add(ToolsRegistry.ADAMANTINE_DRAGON_BONE_HOE, "Adamantine Dragon Bone Hoe");
        translationBuilder.add(WeaponsRegistry.ADAMANTINE_DRAGON_BONE_BATTLEAXE, "Adamantine Dragon Bone Battleaxe");
        translationBuilder.add(WeaponsRegistry.ADAMANTINE_DRAGON_BONE_CAESTUS, "Adamantine Dragon Bone Caestus");
        // translationBuilder.add(WeaponsRegistry.ADAMANTINE_DRAGON_BONE_CLAYMORE, "Adamantine Dragon Bone Claymore");
        // translationBuilder.add(WeaponsRegistry.ADAMANTINE_DRAGON_BONE_DAGGER, "Adamantine Dragon Bone Dagger");
        translationBuilder.add(WeaponsRegistry.ADAMANTINE_DRAGON_BONE_FALCHION, "Adamantine Dragon Bone Falchion");
        // translationBuilder.add(WeaponsRegistry.ADAMANTINE_DRAGON_BONE_GAUNTLET, "Adamantine Dragon Bone Gauntlet");
        translationBuilder.add(WeaponsRegistry.ADAMANTINE_DRAGON_BONE_GLAIVE, "Adamantine Dragon Bone Glaive");
        translationBuilder.add(WeaponsRegistry.ADAMANTINE_DRAGON_BONE_GREATSWORD, "Adamantine Dragon Bone Greatsword");
        // translationBuilder.add(WeaponsRegistry.ADAMANTINE_DRAGON_BONE_HALBERD, "Adamantine Dragon Bone Halberd");
        // translationBuilder.add(WeaponsRegistry.ADAMANTINE_DRAGON_BONE_HANDAXE, "Adamantine Dragon Bone Handaxe");
        // translationBuilder.add(WeaponsRegistry.ADAMANTINE_DRAGON_BONE_LONG_SPEAR, "Adamantine Dragon Bone LONG_SPEAR");
        // translationBuilder.add(WeaponsRegistry.ADAMANTINE_DRAGON_BONE_LONGSWORD, "Adamantine Dragon Bone Longsword");
        translationBuilder.add(WeaponsRegistry.ADAMANTINE_DRAGON_BONE_MACE, "Adamantine Dragon Bone Mace");
        // translationBuilder.add(WeaponsRegistry.ADAMANTINE_DRAGON_BONE_PIKE, "Adamantine Dragon Bone Pike");
        translationBuilder.add(WeaponsRegistry.ADAMANTINE_DRAGON_BONE_QUARTERSTAFF, "Adamantine Dragon Bone Quarterstaff");
        translationBuilder.add(WeaponsRegistry.ADAMANTINE_DRAGON_BONE_RAPIER, "Adamantine Dragon Bone Rapier");
        translationBuilder.add(WeaponsRegistry.ADAMANTINE_DRAGON_BONE_SCIMITAR, "Adamantine Dragon Bone Scimitar");
        translationBuilder.add(WeaponsRegistry.ADAMANTINE_DRAGON_BONE_SCYTHE, "Adamantine Dragon Bone Scythe");
        translationBuilder.add(WeaponsRegistry.ADAMANTINE_DRAGON_BONE_SICKLE, "Adamantine Dragon Bone Sickle");
        translationBuilder.add(WeaponsRegistry.ADAMANTINE_DRAGON_BONE_SPEAR, "Adamantine Dragon Bone Spear");
        translationBuilder.add(WeaponsRegistry.ADAMANTINE_DRAGON_BONE_SWORD, "Adamantine Dragon Bone Sword");
        // translationBuilder.add(WeaponsRegistry.ADAMANTINE_DRAGON_BONE_TRIDENT, "Adamantine Dragon Bone Trident");
        translationBuilder.add(WeaponsRegistry.ADAMANTINE_DRAGON_BONE_WARHAMMER, "Adamantine Dragon Bone War Hammer");

        translationBuilder.add(ToolsRegistry.BONE_PICKAXE, "Bone Pickaxe");
        translationBuilder.add(ToolsRegistry.BONE_AXE, "Bone Axe");
        translationBuilder.add(ToolsRegistry.BONE_SHOVEL, "Bone Shovel");
        translationBuilder.add(ToolsRegistry.BONE_HOE, "Bone Hoe");
        translationBuilder.add(WeaponsRegistry.BONE_BATTLEAXE, "Bone Battleaxe");
        // translationBuilder.add(WeaponsRegistry.BONE_CAESTUS, "Bone Caestus");
        translationBuilder.add(WeaponsRegistry.BONE_CLAYMORE, "Bone Claymore");
        translationBuilder.add(WeaponsRegistry.BONE_DAGGER, "Bone Dagger");
        translationBuilder.add(WeaponsRegistry.BONE_FALCHION, "Bone Falchion");
        // translationBuilder.add(WeaponsRegistry.BONE_GAUNTLET, "Bone Gauntlet");
        translationBuilder.add(WeaponsRegistry.BONE_GLAIVE, "Bone Glaive");
        translationBuilder.add(WeaponsRegistry.BONE_GREATSWORD, "Bone Greatsword");
        translationBuilder.add(WeaponsRegistry.BONE_HALBERD, "Bone Halberd");
        translationBuilder.add(WeaponsRegistry.BONE_HANDAXE, "Bone Handaxe");
        translationBuilder.add(WeaponsRegistry.BONE_LONG_SPEAR, "Bone Long Spear");
        translationBuilder.add(WeaponsRegistry.BONE_LONGSWORD, "Bone Long Sword");
        translationBuilder.add(WeaponsRegistry.BONE_MACE, "Bone Mace");
        translationBuilder.add(WeaponsRegistry.BONE_PIKE, "Bone Pike");
        translationBuilder.add(WeaponsRegistry.BONE_QUARTERSTAFF, "Bone Quarterstaff");
        translationBuilder.add(WeaponsRegistry.BONE_RAPIER, "Bone Rapier");
        translationBuilder.add(WeaponsRegistry.BONE_SCIMITAR, "Bone Scimitar");
        translationBuilder.add(WeaponsRegistry.BONE_SCYTHE, "Bone Scythe");
        translationBuilder.add(WeaponsRegistry.BONE_SICKLE, "Bone Sickle");
        translationBuilder.add(WeaponsRegistry.BONE_SPEAR, "Bone Spear");
        translationBuilder.add(WeaponsRegistry.BONE_SWORD, "Bone Sword");
        translationBuilder.add(WeaponsRegistry.BONE_TRIDENT, "Bone Trident");
        translationBuilder.add(WeaponsRegistry.BONE_WARHAMMER, "Bone Warhammer");

        translationBuilder.add(ToolsRegistry.BRONZE_PICKAXE, "Bronze Pickaxe");
        translationBuilder.add(ToolsRegistry.BRONZE_AXE, "Bronze Axe");
        translationBuilder.add(ToolsRegistry.BRONZE_SHOVEL, "Bronze Shovel");
        translationBuilder.add(ToolsRegistry.BRONZE_HOE, "Bronze Hoe");
        translationBuilder.add(WeaponsRegistry.BRONZE_BATTLEAXE, "Bronze Battleaxe");
        // translationBuilder.add(WeaponsRegistry.BRONZE_CAESTUS, "Bronze Caestus");
        translationBuilder.add(WeaponsRegistry.BRONZE_CLAYMORE, "Bronze Claymore");
        // translationBuilder.add(WeaponsRegistry.BRONZE_DAGGER, "Bronze Dagger");
        translationBuilder.add(WeaponsRegistry.BRONZE_FALCHION, "Bronze Falchion");
        translationBuilder.add(WeaponsRegistry.BRONZE_GAUNTLET, "Bronze Gauntlet");
        translationBuilder.add(WeaponsRegistry.BRONZE_GLAIVE, "Bronze Glaive");
        translationBuilder.add(WeaponsRegistry.BRONZE_GREATSWORD, "Bronze Greatsword");
        translationBuilder.add(WeaponsRegistry.BRONZE_HALBERD, "Bronze Halberd");
        translationBuilder.add(WeaponsRegistry.BRONZE_HANDAXE, "Bronze Handaxe");
        translationBuilder.add(WeaponsRegistry.BRONZE_LONG_SPEAR, "Bronze Long Spear");
        translationBuilder.add(WeaponsRegistry.BRONZE_LONGSWORD, "Bronze Long Sword");
        translationBuilder.add(WeaponsRegistry.BRONZE_MACE, "Bronze Mace");
        translationBuilder.add(WeaponsRegistry.BRONZE_PIKE, "Bronze Pike");
        translationBuilder.add(WeaponsRegistry.BRONZE_QUARTERSTAFF, "Bronze Quarterstaff");
        translationBuilder.add(WeaponsRegistry.BRONZE_RAPIER, "Bronze Rapier");
        translationBuilder.add(WeaponsRegistry.BRONZE_SCIMITAR, "Bronze Scimitar");
        translationBuilder.add(WeaponsRegistry.BRONZE_SCYTHE, "Bronze Scythe");
        translationBuilder.add(WeaponsRegistry.BRONZE_SICKLE, "Bronze Sickle");
        translationBuilder.add(WeaponsRegistry.BRONZE_SPEAR, "Bronze Spear");
        translationBuilder.add(WeaponsRegistry.BRONZE_SWORD, "Bronze Sword");
        translationBuilder.add(WeaponsRegistry.BRONZE_TRIDENT, "Bronze Trident");
        translationBuilder.add(WeaponsRegistry.BRONZE_WARHAMMER, "Bronze Warhammer");

        translationBuilder.add(ToolsRegistry.COLD_IRON_PICKAXE, "Cold Iron Pickaxe");
        translationBuilder.add(ToolsRegistry.COLD_IRON_AXE, "Cold Iron Axe");
        translationBuilder.add(ToolsRegistry.COLD_IRON_SHOVEL, "Cold Iron Shovel");
        translationBuilder.add(ToolsRegistry.COLD_IRON_HOE, "Cold Iron Hoe");
        translationBuilder.add(WeaponsRegistry.COLD_IRON_BATTLEAXE, "Cold Iron Battleaxe");
        // translationBuilder.add(WeaponsRegistry.COLD_IRON_CAESTUS, "Cold Iron Caestus");
        translationBuilder.add(WeaponsRegistry.COLD_IRON_CLAYMORE, "Cold Iron Claymore");
        translationBuilder.add(WeaponsRegistry.COLD_IRON_DAGGER, "Cold Iron Dagger");
        translationBuilder.add(WeaponsRegistry.COLD_IRON_FALCHION, "Cold Iron Falchion");
        translationBuilder.add(WeaponsRegistry.COLD_IRON_GAUNTLET, "Cold Iron Gauntlet");
        translationBuilder.add(WeaponsRegistry.COLD_IRON_GLAIVE, "Cold Iron Glaive");
        translationBuilder.add(WeaponsRegistry.COLD_IRON_GREATSWORD, "Cold Iron Greatsword");
        translationBuilder.add(WeaponsRegistry.COLD_IRON_HALBERD, "Cold Iron Halberd");
        translationBuilder.add(WeaponsRegistry.COLD_IRON_HANDAXE, "Cold Iron Handaxe");
        translationBuilder.add(WeaponsRegistry.COLD_IRON_LONG_SPEAR, "Cold Iron Long Spear");
        translationBuilder.add(WeaponsRegistry.COLD_IRON_LONGSWORD, "Cold Iron Long Sword");
        translationBuilder.add(WeaponsRegistry.COLD_IRON_MACE, "Cold Iron Mace");
        translationBuilder.add(WeaponsRegistry.COLD_IRON_PIKE, "Cold Iron Pike");
        translationBuilder.add(WeaponsRegistry.COLD_IRON_QUARTERSTAFF, "Cold Iron Quarterstaff");
        translationBuilder.add(WeaponsRegistry.COLD_IRON_RAPIER, "Cold Iron Rapier");
        translationBuilder.add(WeaponsRegistry.COLD_IRON_SCIMITAR, "Cold Iron Scimitar");
        translationBuilder.add(WeaponsRegistry.COLD_IRON_SCYTHE, "Cold Iron Scythe");
        translationBuilder.add(WeaponsRegistry.COLD_IRON_SICKLE, "Cold Iron Sickle");
        translationBuilder.add(WeaponsRegistry.COLD_IRON_SPEAR, "Cold Iron Spear");
        translationBuilder.add(WeaponsRegistry.COLD_IRON_SWORD, "Cold Iron Sword");
        translationBuilder.add(WeaponsRegistry.COLD_IRON_TRIDENT, "Cold Iron Trident");
        translationBuilder.add(WeaponsRegistry.COLD_IRON_WARHAMMER, "Cold Iron Warhammer");

        translationBuilder.add(ToolsRegistry.COPPER_PICKAXE, "Copper Pickaxe");
        translationBuilder.add(ToolsRegistry.COPPER_AXE, "Copper Axe");
        translationBuilder.add(ToolsRegistry.COPPER_SHOVEL, "Copper Shovel");
        translationBuilder.add(ToolsRegistry.COPPER_HOE, "Copper Hoe");
        translationBuilder.add(WeaponsRegistry.COPPER_BATTLEAXE, "Copper Battleaxe");
        // translationBuilder.add(WeaponsRegistry.COPPER_CAESTUS, "Copper Caestus");
        translationBuilder.add(WeaponsRegistry.COPPER_CLAYMORE, "Copper Claymore");
        translationBuilder.add(WeaponsRegistry.COPPER_DAGGER, "Copper Dagger");
        translationBuilder.add(WeaponsRegistry.COPPER_FALCHION, "Copper Falchion");
        translationBuilder.add(WeaponsRegistry.COPPER_GAUNTLET, "Copper Gauntlet");
        translationBuilder.add(WeaponsRegistry.COPPER_GLAIVE, "Copper Glaive");
        translationBuilder.add(WeaponsRegistry.COPPER_GREATSWORD, "Copper Greatsword");
        translationBuilder.add(WeaponsRegistry.COPPER_HALBERD, "Copper Halberd");
        translationBuilder.add(WeaponsRegistry.COPPER_HANDAXE, "Copper Handaxe");
        translationBuilder.add(WeaponsRegistry.COPPER_LONG_SPEAR, "Copper Long Spear");
        translationBuilder.add(WeaponsRegistry.COPPER_LONGSWORD, "Copper Long Sword");
        translationBuilder.add(WeaponsRegistry.COPPER_MACE, "Copper Mace");
        translationBuilder.add(WeaponsRegistry.COPPER_PIKE, "Copper Pike");
        translationBuilder.add(WeaponsRegistry.COPPER_QUARTERSTAFF, "Copper Quarterstaff");
        translationBuilder.add(WeaponsRegistry.COPPER_RAPIER, "Copper Rapier");
        translationBuilder.add(WeaponsRegistry.COPPER_SCIMITAR, "Copper Scimitar");
        translationBuilder.add(WeaponsRegistry.COPPER_SCYTHE, "Copper Scythe");
        translationBuilder.add(WeaponsRegistry.COPPER_SICKLE, "Copper Sickle");
        translationBuilder.add(WeaponsRegistry.COPPER_SPEAR, "Copper Spear");
        translationBuilder.add(WeaponsRegistry.COPPER_SWORD, "Copper Sword");
        translationBuilder.add(WeaponsRegistry.COPPER_TRIDENT, "Copper Trident");
        translationBuilder.add(WeaponsRegistry.COPPER_WARHAMMER, "Copper Warhammer");

        translationBuilder.add(ToolsRegistry.DARK_STEEL_PICKAXE, "Dark Steel Pickaxe");
        translationBuilder.add(ToolsRegistry.DARK_STEEL_AXE, "Dark Steel Axe");
        translationBuilder.add(ToolsRegistry.DARK_STEEL_SHOVEL, "Dark Steel Shovel");
        translationBuilder.add(ToolsRegistry.DARK_STEEL_HOE, "Dark Steel Hoe");
        translationBuilder.add(WeaponsRegistry.DARK_STEEL_BATTLEAXE, "Dark Steel Battleaxe");
        // translationBuilder.add(WeaponsRegistry.DARK_STEEL_CAESTUS, "Dark Steel Caestus");
        translationBuilder.add(WeaponsRegistry.DARK_STEEL_CLAYMORE, "Dark Steel Claymore");
        translationBuilder.add(WeaponsRegistry.DARK_STEEL_DAGGER, "Dark Steel Dagger");
        translationBuilder.add(WeaponsRegistry.DARK_STEEL_FALCHION, "Dark Steel Falchion");
        translationBuilder.add(WeaponsRegistry.DARK_STEEL_GAUNTLET, "Dark Steel Gauntlet");
        translationBuilder.add(WeaponsRegistry.DARK_STEEL_GLAIVE, "Dark Steel Glaive");
        translationBuilder.add(WeaponsRegistry.DARK_STEEL_GREATSWORD, "Dark Steel Greatsword");
        translationBuilder.add(WeaponsRegistry.DARK_STEEL_HALBERD, "Dark Steel Halberd");
        translationBuilder.add(WeaponsRegistry.DARK_STEEL_HANDAXE, "Dark Steel Handaxe");
        translationBuilder.add(WeaponsRegistry.DARK_STEEL_LONG_SPEAR, "Dark Steel Long Spear");
        translationBuilder.add(WeaponsRegistry.DARK_STEEL_LONGSWORD, "Dark Steel Long Sword");
        translationBuilder.add(WeaponsRegistry.DARK_STEEL_MACE, "Dark Steel Mace");
        translationBuilder.add(WeaponsRegistry.DARK_STEEL_PIKE, "Dark Steel Pike");
        translationBuilder.add(WeaponsRegistry.DARK_STEEL_QUARTERSTAFF, "Dark Steel Quarterstaff");
        translationBuilder.add(WeaponsRegistry.DARK_STEEL_RAPIER, "Dark Steel Rapier");
        translationBuilder.add(WeaponsRegistry.DARK_STEEL_SCIMITAR, "Dark Steel Scimitar");
        translationBuilder.add(WeaponsRegistry.DARK_STEEL_SCYTHE, "Dark Steel Scythe");
        translationBuilder.add(WeaponsRegistry.DARK_STEEL_SICKLE, "Dark Steel Sickle");
        translationBuilder.add(WeaponsRegistry.DARK_STEEL_SPEAR, "Dark Steel Spear");
        translationBuilder.add(WeaponsRegistry.DARK_STEEL_SWORD, "Dark Steel Sword");
        translationBuilder.add(WeaponsRegistry.DARK_STEEL_TRIDENT, "Dark Steel Trident");
        translationBuilder.add(WeaponsRegistry.DARK_STEEL_WARHAMMER, "Dark Steel Warhammer");

        translationBuilder.add(WeaponsRegistry.DIAMOND_BATTLEAXE, "Diamond Battleaxe");
        // translationBuilder.add(WeaponsRegistry.DIAMOND_CAESTUS, "Diamond Caestus");
        translationBuilder.add(WeaponsRegistry.DIAMOND_CLAYMORE, "Diamond Claymore");
        translationBuilder.add(WeaponsRegistry.DIAMOND_DAGGER, "Diamond Dagger");
        translationBuilder.add(WeaponsRegistry.DIAMOND_FALCHION, "Diamond Falchion");
        translationBuilder.add(WeaponsRegistry.DIAMOND_GAUNTLET, "Diamond Gauntlet");
        translationBuilder.add(WeaponsRegistry.DIAMOND_GLAIVE, "Diamond Glaive");
        translationBuilder.add(WeaponsRegistry.DIAMOND_GREATSWORD, "Diamond Greatsword");
        translationBuilder.add(WeaponsRegistry.DIAMOND_HALBERD, "Diamond Halberd");
        translationBuilder.add(WeaponsRegistry.DIAMOND_HANDAXE, "Diamond Handaxe");
        translationBuilder.add(WeaponsRegistry.DIAMOND_LONG_SPEAR, "Diamond Long Spear");
        translationBuilder.add(WeaponsRegistry.DIAMOND_LONGSWORD, "Diamond Long Sword");
        translationBuilder.add(WeaponsRegistry.DIAMOND_MACE, "Diamond Mace");
        translationBuilder.add(WeaponsRegistry.DIAMOND_PIKE, "Diamond Pike");
        translationBuilder.add(WeaponsRegistry.DIAMOND_QUARTERSTAFF, "Diamond Quarterstaff");
        translationBuilder.add(WeaponsRegistry.DIAMOND_RAPIER, "Diamond Rapier");
        translationBuilder.add(WeaponsRegistry.DIAMOND_SCIMITAR, "Diamond Scimitar");
        translationBuilder.add(WeaponsRegistry.DIAMOND_SCYTHE, "Diamond Scythe");
        translationBuilder.add(WeaponsRegistry.DIAMOND_SICKLE, "Diamond Sickle");
        translationBuilder.add(WeaponsRegistry.DIAMOND_SPEAR, "Diamond Spear");
        translationBuilder.add(WeaponsRegistry.DIAMOND_TRIDENT, "Diamond Trident");
        translationBuilder.add(WeaponsRegistry.DIAMOND_WARHAMMER, "Diamond Warhammer");

        translationBuilder.add(ToolsRegistry.DRAGON_BONE_PICKAXE, "Dragon Bone Pickaxe");
        translationBuilder.add(ToolsRegistry.DRAGON_BONE_AXE, "Dragon Bone Axe");
        translationBuilder.add(ToolsRegistry.DRAGON_BONE_SHOVEL, "Dragon Bone Shovel");
        translationBuilder.add(ToolsRegistry.DRAGON_BONE_HOE, "Dragon Bone Hoe");
        translationBuilder.add(WeaponsRegistry.DRAGON_BONE_BATTLEAXE, "Dragon Bone Battleaxe");
        // translationBuilder.add(WeaponsRegistry.DRAGON_BONE_CAESTUS, "Dragon Bone Caestus");
        translationBuilder.add(WeaponsRegistry.DRAGON_BONE_CLAYMORE, "Dragon Bone Claymore");
        translationBuilder.add(WeaponsRegistry.DRAGON_BONE_DAGGER, "Dragon Bone Dagger");
        translationBuilder.add(WeaponsRegistry.DRAGON_BONE_FALCHION, "Dragon Bone Falchion");
        // translationBuilder.add(WeaponsRegistry.DRAGON_BONE_GAUNTLET, "Dragon Bone Gauntlet");
        translationBuilder.add(WeaponsRegistry.DRAGON_BONE_GLAIVE, "Dragon Bone Glaive");
        translationBuilder.add(WeaponsRegistry.DRAGON_BONE_GREATSWORD, "Dragon Bone Greatsword");
        translationBuilder.add(WeaponsRegistry.DRAGON_BONE_HALBERD, "Dragon Bone Halberd");
        translationBuilder.add(WeaponsRegistry.DRAGON_BONE_HANDAXE, "Dragon Bone Handaxe");
        translationBuilder.add(WeaponsRegistry.DRAGON_BONE_LONG_SPEAR, "Dragon Bone Long Spear");
        translationBuilder.add(WeaponsRegistry.DRAGON_BONE_LONGSWORD, "Dragon Bone Longsword");
        translationBuilder.add(WeaponsRegistry.DRAGON_BONE_MACE, "Dragon Bone Mace");
        translationBuilder.add(WeaponsRegistry.DRAGON_BONE_PIKE, "Dragon Bone Pike");
        translationBuilder.add(WeaponsRegistry.DRAGON_BONE_QUARTERSTAFF, "Dragon Bone Quarterstaff");
        translationBuilder.add(WeaponsRegistry.DRAGON_BONE_RAPIER, "Dragon Bone Rapier");
        translationBuilder.add(WeaponsRegistry.DRAGON_BONE_SCIMITAR, "Dragon Bone Scimitar");
        translationBuilder.add(WeaponsRegistry.DRAGON_BONE_SCYTHE, "Dragon Bone Scythe");
        translationBuilder.add(WeaponsRegistry.DRAGON_BONE_SICKLE, "Dragon Bone Sickle");
        translationBuilder.add(WeaponsRegistry.DRAGON_BONE_SPEAR, "Dragon Bone Spear");
        translationBuilder.add(WeaponsRegistry.DRAGON_BONE_SWORD, "Dragon Bone Sword");
        translationBuilder.add(WeaponsRegistry.DRAGON_BONE_TRIDENT, "Dragon Bone Trident");
        translationBuilder.add(WeaponsRegistry.DRAGON_BONE_WARHAMMER, "Dragon Bone Warhammer");

        translationBuilder.add(WeaponsRegistry.DRAGON_CLAW, "Dragon Claw");
        translationBuilder.add(WeaponsRegistry.DRAGON_SCALE_CAESTUS, "Dragon Scale Caestus");

        translationBuilder.add(ToolsRegistry.ELVEN_STEEL_PICKAXE, "Elven Steel Pickaxe");
        translationBuilder.add(ToolsRegistry.ELVEN_STEEL_AXE, "Elven Steel Axe");
        translationBuilder.add(ToolsRegistry.ELVEN_STEEL_SHOVEL, "Elven Steel Shovel");
        translationBuilder.add(ToolsRegistry.ELVEN_STEEL_HOE, "Elven Steel Hoe");
        translationBuilder.add(WeaponsRegistry.ELVEN_STEEL_BATTLEAXE, "Elven Steel Battleaxe");
        // translationBuilder.add(WeaponsRegistry.ELVEN_STEEL_CAESTUS, "Elven Steel Caestus");
        translationBuilder.add(WeaponsRegistry.ELVEN_STEEL_CLAYMORE, "Elven Steel Claymore");
        translationBuilder.add(WeaponsRegistry.ELVEN_STEEL_DAGGER, "Elven Steel Dagger");
        translationBuilder.add(WeaponsRegistry.ELVEN_STEEL_FALCHION, "Elven Steel Falchion");
        translationBuilder.add(WeaponsRegistry.ELVEN_STEEL_GAUNTLET, "Elven Steel Gauntlet");
        translationBuilder.add(WeaponsRegistry.ELVEN_STEEL_GLAIVE, "Elven Steel Glaive");
        translationBuilder.add(WeaponsRegistry.ELVEN_STEEL_GREATSWORD, "Elven Steel Greatsword");
        translationBuilder.add(WeaponsRegistry.ELVEN_STEEL_HALBERD, "Elven Steel Halberd");
        translationBuilder.add(WeaponsRegistry.ELVEN_STEEL_HANDAXE, "Elven Steel Handaxe");
        translationBuilder.add(WeaponsRegistry.ELVEN_STEEL_LONG_SPEAR, "Elven Steel Long Spear");
        translationBuilder.add(WeaponsRegistry.ELVEN_STEEL_LONGSWORD, "Elven Steel Longsword");
        translationBuilder.add(WeaponsRegistry.ELVEN_STEEL_MACE, "Elven Steel Mace");
        translationBuilder.add(WeaponsRegistry.ELVEN_STEEL_PIKE, "Elven Steel Pike");
        translationBuilder.add(WeaponsRegistry.ELVEN_STEEL_QUARTERSTAFF, "Elven Steel Quarterstaff");
        translationBuilder.add(WeaponsRegistry.ELVEN_STEEL_RAPIER, "Elven Steel Rapier");
        translationBuilder.add(WeaponsRegistry.ELVEN_STEEL_SCIMITAR, "Elven Steel Scimitar");
        translationBuilder.add(WeaponsRegistry.ELVEN_STEEL_SCYTHE, "Elven Steel Scythe");
        translationBuilder.add(WeaponsRegistry.ELVEN_STEEL_SICKLE, "Elven Steel Sickle");
        translationBuilder.add(WeaponsRegistry.ELVEN_STEEL_SPEAR, "Elven Steel Spear");
        translationBuilder.add(WeaponsRegistry.ELVEN_STEEL_SWORD, "Elven Steel Sword");
        translationBuilder.add(WeaponsRegistry.ELVEN_STEEL_TRIDENT, "Elven Steel Trident");
        translationBuilder.add(WeaponsRegistry.ELVEN_STEEL_WARHAMMER, "Elven Steel Warhammer");

        translationBuilder.add(WeaponsRegistry.GOLDEN_BATTLEAXE, "Golden Battleaxe");
        // translationBuilder.add(WeaponsRegistry.GOLDEN_CAESTUS, "Golden Caestus");
        translationBuilder.add(WeaponsRegistry.GOLDEN_CLAYMORE, "Golden Claymore");
        translationBuilder.add(WeaponsRegistry.GOLDEN_DAGGER, "Golden Dagger");
        translationBuilder.add(WeaponsRegistry.GOLDEN_FALCHION, "Golden Falchion");
        translationBuilder.add(WeaponsRegistry.GOLDEN_GAUNTLET, "Golden Gauntlet");
        translationBuilder.add(WeaponsRegistry.GOLDEN_GLAIVE, "Golden Glaive");
        translationBuilder.add(WeaponsRegistry.GOLDEN_GREATSWORD, "Golden Greatsword");
        translationBuilder.add(WeaponsRegistry.GOLDEN_HALBERD, "Golden Halberd");
        translationBuilder.add(WeaponsRegistry.GOLDEN_HANDAXE, "Golden Handaxe");
        translationBuilder.add(WeaponsRegistry.GOLDEN_LONG_SPEAR, "Golden Long Spear");
        translationBuilder.add(WeaponsRegistry.GOLDEN_LONGSWORD, "Golden Longsword");
        translationBuilder.add(WeaponsRegistry.GOLDEN_MACE, "Golden Mace");
        translationBuilder.add(WeaponsRegistry.GOLDEN_PIKE, "Golden Pike");
        translationBuilder.add(WeaponsRegistry.GOLDEN_QUARTERSTAFF, "Golden Quarterstaff");
        translationBuilder.add(WeaponsRegistry.GOLDEN_RAPIER, "Golden Rapier");
        translationBuilder.add(WeaponsRegistry.GOLDEN_SCIMITAR, "Golden Scimitar");
        translationBuilder.add(WeaponsRegistry.GOLDEN_SCYTHE, "Golden Scythe");
        translationBuilder.add(WeaponsRegistry.GOLDEN_SICKLE, "Golden Sickle");
        translationBuilder.add(WeaponsRegistry.GOLDEN_SPEAR, "Golden Spear");
        translationBuilder.add(WeaponsRegistry.GOLDEN_TRIDENT, "Golden Trident");
        translationBuilder.add(WeaponsRegistry.GOLDEN_WARHAMMER, "Golden Warhammer");

        translationBuilder.add(ToolsRegistry.INFERNAL_IRON_PICKAXE, "Infernal Iron Pickaxe");
        translationBuilder.add(ToolsRegistry.INFERNAL_IRON_AXE, "Infernal Iron Axe");
        translationBuilder.add(ToolsRegistry.INFERNAL_IRON_SHOVEL, "Infernal Iron Shovel");
        translationBuilder.add(ToolsRegistry.INFERNAL_IRON_HOE, "Infernal Iron Hoe");
        translationBuilder.add(WeaponsRegistry.INFERNAL_IRON_BATTLEAXE, "Infernal Iron Battleaxe");
        // translationBuilder.add(WeaponsRegistry.INFERNAL_IRON_CAESTUS, "Infernal Iron Caestus");
        translationBuilder.add(WeaponsRegistry.INFERNAL_IRON_CLAYMORE, "Infernal Iron Claymore");
        translationBuilder.add(WeaponsRegistry.INFERNAL_IRON_DAGGER, "Infernal Iron Dagger");
        translationBuilder.add(WeaponsRegistry.INFERNAL_IRON_FALCHION, "Infernal Iron Falchion");
        translationBuilder.add(WeaponsRegistry.INFERNAL_IRON_GAUNTLET, "Infernal Iron Gauntlet");
        // translationBuilder.add(WeaponsRegistry.INFERNAL_IRON_GLAIVE, "Infernal Iron Glaive");
        translationBuilder.add(WeaponsRegistry.INFERNAL_IRON_GREATSWORD, "Infernal Iron Greatsword");
        translationBuilder.add(WeaponsRegistry.INFERNAL_IRON_HALBERD, "Infernal Iron Halberd");
        translationBuilder.add(WeaponsRegistry.INFERNAL_IRON_HANDAXE, "Infernal Iron Handaxe");
        translationBuilder.add(WeaponsRegistry.INFERNAL_IRON_LONG_SPEAR, "Infernal Iron Long Spear");
        translationBuilder.add(WeaponsRegistry.INFERNAL_IRON_LONGSWORD, "Infernal Iron Longsword");
        translationBuilder.add(WeaponsRegistry.INFERNAL_IRON_MACE, "Infernal Iron Mace");
        translationBuilder.add(WeaponsRegistry.INFERNAL_IRON_PIKE, "Infernal Iron Pike");
        translationBuilder.add(WeaponsRegistry.INFERNAL_IRON_QUARTERSTAFF, "Infernal Iron Quarterstaff");
        translationBuilder.add(WeaponsRegistry.INFERNAL_IRON_RAPIER, "Infernal Iron Rapier");
        translationBuilder.add(WeaponsRegistry.INFERNAL_IRON_SCIMITAR, "Infernal Iron Scimitar");
        translationBuilder.add(WeaponsRegistry.INFERNAL_IRON_SCYTHE, "Infernal Iron Scythe");
        translationBuilder.add(WeaponsRegistry.INFERNAL_IRON_SICKLE, "Infernal Iron Sickle");
        translationBuilder.add(WeaponsRegistry.INFERNAL_IRON_SPEAR, "Infernal Iron Spear");
        translationBuilder.add(WeaponsRegistry.INFERNAL_IRON_SWORD, "Infernal Iron Sword");
        translationBuilder.add(WeaponsRegistry.INFERNAL_IRON_TRIDENT, "Infernal Iron Trident");
        translationBuilder.add(WeaponsRegistry.INFERNAL_IRON_WARHAMMER, "Infernal Iron Warhammer");

        translationBuilder.add(WeaponsRegistry.IRON_BATTLEAXE, "Iron Battleaxe");
        // translationBuilder.add(WeaponsRegistry.IRON_CAESTUS, "Iron Caestus");
        translationBuilder.add(WeaponsRegistry.IRON_CLAYMORE, "Iron Claymore");
        translationBuilder.add(WeaponsRegistry.IRON_DAGGER, "Iron Dagger");
        translationBuilder.add(WeaponsRegistry.IRON_FALCHION, "Iron Falchion");
        translationBuilder.add(WeaponsRegistry.IRON_GAUNTLET, "Iron Gauntlet");
        translationBuilder.add(WeaponsRegistry.IRON_GLAIVE, "Iron Glaive");
        translationBuilder.add(WeaponsRegistry.IRON_GREATSWORD, "Iron Greatsword");
        translationBuilder.add(WeaponsRegistry.IRON_HALBERD, "Iron Halberd");
        translationBuilder.add(WeaponsRegistry.IRON_HANDAXE, "Iron Handaxe");
        translationBuilder.add(WeaponsRegistry.IRON_LONG_SPEAR, "Iron Long Spear");
        translationBuilder.add(WeaponsRegistry.IRON_LONGSWORD, "Iron Longsword");
        translationBuilder.add(WeaponsRegistry.IRON_MACE, "Iron Mace");
        translationBuilder.add(WeaponsRegistry.IRON_PIKE, "Iron Pike");
        translationBuilder.add(WeaponsRegistry.IRON_QUARTERSTAFF, "Iron Quarterstaff");
        translationBuilder.add(WeaponsRegistry.IRON_RAPIER, "Iron Rapier");
        translationBuilder.add(WeaponsRegistry.IRON_SCIMITAR, "Iron Scimitar");
        translationBuilder.add(WeaponsRegistry.IRON_SCYTHE, "Iron Scythe");
        translationBuilder.add(WeaponsRegistry.IRON_SICKLE, "Iron Sickle");
        translationBuilder.add(WeaponsRegistry.IRON_SPEAR, "Iron Spear");
        translationBuilder.add(WeaponsRegistry.IRON_TRIDENT, "Iron Trident");
        translationBuilder.add(WeaponsRegistry.IRON_WARHAMMER, "Iron Warhammer");

        // translationBuilder.add(ToolsRegistry.ITANIUM_PICKAXE, "Itanium Pickaxe");
        // translationBuilder.add(ToolsRegistry.ITANIUM_AXE, "Itanium Axe");
        // translationBuilder.add(ToolsRegistry.ITANIUM_SHOVEL, "Itanium Shovel");
        // translationBuilder.add(ToolsRegistry.ITANIUM_HOE, "Itanium Hoe");
        // translationBuilder.add(WeaponsRegistry.ITANIUM_BATTLEAXE, "Itanium Battleaxe");
        // translationBuilder.add(WeaponsRegistry.ITANIUM_CAESTUS, "Itanium Caestus");
        translationBuilder.add(WeaponsRegistry.ITANIUM_CLAYMORE, "Itanium Claymore");
        // translationBuilder.add(WeaponsRegistry.ITANIUM_DAGGER, "Itanium Dagger");
        // translationBuilder.add(WeaponsRegistry.ITANIUM_FALCHION, "Itanium Falchion");
        // translationBuilder.add(WeaponsRegistry.ITANIUM_GAUNTLET, "Itanium Gauntlet");
        // translationBuilder.add(WeaponsRegistry.ITANIUM_GLAIVE, "Itanium Glaive");
        // translationBuilder.add(WeaponsRegistry.ITANIUM_GREATSWORD, "Itanium Greatsword");
        translationBuilder.add(WeaponsRegistry.ITANIUM_HALBERD, "Itanium Halberd");
        translationBuilder.add(WeaponsRegistry.ITANIUM_HANDAXE, "Itanium Handaxe");
        translationBuilder.add(WeaponsRegistry.ITANIUM_LONG_SPEAR, "Itanium Long Spear");
        translationBuilder.add(WeaponsRegistry.ITANIUM_LONGSWORD, "Itanium Longsword");
        // translationBuilder.add(WeaponsRegistry.ITANIUM_MACE, "Itanium Mace");
        // translationBuilder.add(WeaponsRegistry.ITANIUM_PIKE, "Itanium Pike");
        // translationBuilder.add(WeaponsRegistry.ITANIUM_QUARTERSTAFF, "Itanium Quarterstaff");
        // translationBuilder.add(WeaponsRegistry.ITANIUM_RAPIER, "Itanium Rapier");
        // translationBuilder.add(WeaponsRegistry.ITANIUM_SCIMITAR, "Itanium Scimitar");
        // translationBuilder.add(WeaponsRegistry.ITANIUM_SCYTHE, "Itanium Scythe");
        // translationBuilder.add(WeaponsRegistry.ITANIUM_SICKLE, "Itanium Sickle");
        // translationBuilder.add(WeaponsRegistry.ITANIUM_SPEAR, "Itanium Spear");
        // translationBuilder.add(WeaponsRegistry.ITANIUM_SWORD, "Itanium Sword");
        // translationBuilder.add(WeaponsRegistry.ITANIUM_TRIDENT, "Itanium Trident");
        // translationBuilder.add(WeaponsRegistry.ITANIUM_WARHAMMER, "Itanium Warhammer");

        translationBuilder.add(WeaponsRegistry.LEATHER_CAESTUS, "Leather Caestus");

        translationBuilder.add(ToolsRegistry.MITHRIL_PICKAXE, "Mithril Pickaxe");
        translationBuilder.add(ToolsRegistry.MITHRIL_AXE, "Mithril Axe");
        translationBuilder.add(ToolsRegistry.MITHRIL_SHOVEL, "Mithril Shovel");
        translationBuilder.add(ToolsRegistry.MITHRIL_HOE, "Mithril Hoe");
        translationBuilder.add(WeaponsRegistry.MITHRIL_BATTLEAXE, "Mithril Battleaxe");
        // translationBuilder.add(WeaponsRegistry.MITHRIL_CAESTUS, "Mithril Caestus");
        translationBuilder.add(WeaponsRegistry.MITHRIL_CLAYMORE, "Mithril Claymore");
        translationBuilder.add(WeaponsRegistry.MITHRIL_DAGGER, "Mithril Dagger");
        translationBuilder.add(WeaponsRegistry.MITHRIL_FALCHION, "Mithril Falchion");
        translationBuilder.add(WeaponsRegistry.MITHRIL_GAUNTLET, "Mithril Gauntlet");
        translationBuilder.add(WeaponsRegistry.MITHRIL_GLAIVE, "Mithril Glaive");
        translationBuilder.add(WeaponsRegistry.MITHRIL_GREATSWORD, "Mithril Greatsword");
        translationBuilder.add(WeaponsRegistry.MITHRIL_HALBERD, "Mithril Halberd");
        translationBuilder.add(WeaponsRegistry.MITHRIL_HANDAXE, "Mithril Handaxe");
        translationBuilder.add(WeaponsRegistry.MITHRIL_LONG_SPEAR, "Mithril Long Spear");
        translationBuilder.add(WeaponsRegistry.MITHRIL_LONGSWORD, "Mithril Longsword");
        translationBuilder.add(WeaponsRegistry.MITHRIL_MACE, "Mithril Mace");
        translationBuilder.add(WeaponsRegistry.MITHRIL_PIKE, "Mithril Pike");
        translationBuilder.add(WeaponsRegistry.MITHRIL_QUARTERSTAFF, "Mithril Quarterstaff");
        translationBuilder.add(WeaponsRegistry.MITHRIL_RAPIER, "Mithril Rapier");
        translationBuilder.add(WeaponsRegistry.MITHRIL_SCIMITAR, "Mithril Scimitar");
        translationBuilder.add(WeaponsRegistry.MITHRIL_SCYTHE, "Mithril Scythe");
        translationBuilder.add(WeaponsRegistry.MITHRIL_SICKLE, "Mithril Sickle");
        translationBuilder.add(WeaponsRegistry.MITHRIL_SPEAR, "Mithril Spear");
        translationBuilder.add(WeaponsRegistry.MITHRIL_SWORD, "Mithril Sword");
        translationBuilder.add(WeaponsRegistry.MITHRIL_TRIDENT, "Mithril Trident");
        translationBuilder.add(WeaponsRegistry.MITHRIL_WARHAMMER, "Mithril Warhammer");

        translationBuilder.add(WeaponsRegistry.NETHERITE_BATTLEAXE, "Netherite Battleaxe");
        // translationBuilder.add(WeaponsRegistry.NETHERITE_CAESTUS, "Netherite Caestus");
        translationBuilder.add(WeaponsRegistry.NETHERITE_CLAYMORE, "Netherite Claymore");
        translationBuilder.add(WeaponsRegistry.NETHERITE_DAGGER, "Netherite Dagger");
        translationBuilder.add(WeaponsRegistry.NETHERITE_FALCHION, "Netherite Falchion");
        translationBuilder.add(WeaponsRegistry.NETHERITE_GAUNTLET, "Netherite Gauntlet");
        translationBuilder.add(WeaponsRegistry.NETHERITE_GLAIVE, "Netherite Glaive");
        translationBuilder.add(WeaponsRegistry.NETHERITE_GREATSWORD, "Netherite Greatsword");
        translationBuilder.add(WeaponsRegistry.NETHERITE_HALBERD, "Netherite Halberd");
        translationBuilder.add(WeaponsRegistry.NETHERITE_HANDAXE, "Netherite Handaxe");
        translationBuilder.add(WeaponsRegistry.NETHERITE_LONG_SPEAR, "Netherite Long Spear");
        translationBuilder.add(WeaponsRegistry.NETHERITE_LONGSWORD, "Netherite Longsword");
        translationBuilder.add(WeaponsRegistry.NETHERITE_MACE, "Netherite Mace");
        translationBuilder.add(WeaponsRegistry.NETHERITE_PIKE, "Netherite Pike");
        translationBuilder.add(WeaponsRegistry.NETHERITE_QUARTERSTAFF, "Netherite Quarterstaff");
        translationBuilder.add(WeaponsRegistry.NETHERITE_RAPIER, "Netherite Rapier");
        translationBuilder.add(WeaponsRegistry.NETHERITE_SCIMITAR, "Netherite Scimitar");
        translationBuilder.add(WeaponsRegistry.NETHERITE_SCYTHE, "Netherite Scythe");
        translationBuilder.add(WeaponsRegistry.NETHERITE_SICKLE, "Netherite Sickle");
        translationBuilder.add(WeaponsRegistry.NETHERITE_SPEAR, "Netherite Spear");
        translationBuilder.add(WeaponsRegistry.NETHERITE_TRIDENT, "Netherite Trident");
        translationBuilder.add(WeaponsRegistry.NETHERITE_WARHAMMER, "Netherite Warhammer");

        translationBuilder.add(ToolsRegistry.PALLADIUM_PICKAXE, "Palladium Pickaxe");
        translationBuilder.add(ToolsRegistry.PALLADIUM_AXE, "Palladium Axe");
        translationBuilder.add(ToolsRegistry.PALLADIUM_SHOVEL, "Palladium Shovel");
        translationBuilder.add(ToolsRegistry.PALLADIUM_HOE, "Palladium Hoe");
        translationBuilder.add(WeaponsRegistry.PALLADIUM_BATTLEAXE, "Palladium Battleaxe");
        // translationBuilder.add(WeaponsRegistry.PALLADIUM_CAESTUS, "Palladium Caestus");
        translationBuilder.add(WeaponsRegistry.PALLADIUM_CLAYMORE, "Palladium Claymore");
        translationBuilder.add(WeaponsRegistry.PALLADIUM_DAGGER, "Palladium Dagger");
        translationBuilder.add(WeaponsRegistry.PALLADIUM_FALCHION, "Palladium Falchion");
        translationBuilder.add(WeaponsRegistry.PALLADIUM_GAUNTLET, "Palladium Gauntlet");
        translationBuilder.add(WeaponsRegistry.PALLADIUM_GREATSWORD, "Palladium Greatsword");
        translationBuilder.add(WeaponsRegistry.PALLADIUM_GLAIVE, "Palladium Glaive");
        translationBuilder.add(WeaponsRegistry.PALLADIUM_HALBERD, "Palladium Halberd");
        translationBuilder.add(WeaponsRegistry.PALLADIUM_HANDAXE, "Palladium Handaxe");
        translationBuilder.add(WeaponsRegistry.PALLADIUM_LONG_SPEAR, "Palladium Long Spear");
        translationBuilder.add(WeaponsRegistry.PALLADIUM_LONGSWORD, "Palladium Longsword");
        translationBuilder.add(WeaponsRegistry.PALLADIUM_MACE, "Palladium Mace");
        translationBuilder.add(WeaponsRegistry.PALLADIUM_PIKE, "Palladium Pike");
        translationBuilder.add(WeaponsRegistry.PALLADIUM_QUARTERSTAFF, "Palladium Quarterstaff");
        translationBuilder.add(WeaponsRegistry.PALLADIUM_RAPIER, "Palladium Rapier");
        translationBuilder.add(WeaponsRegistry.PALLADIUM_SCIMITAR, "Palladium Scimitar");
        translationBuilder.add(WeaponsRegistry.PALLADIUM_SCYTHE, "Palladium Scythe");
        translationBuilder.add(WeaponsRegistry.PALLADIUM_SPEAR, "Palladium Spear");
        translationBuilder.add(WeaponsRegistry.PALLADIUM_SWORD, "Palladium Sword");
        translationBuilder.add(WeaponsRegistry.PALLADIUM_SICKLE, "Palladium Sickle");
        translationBuilder.add(WeaponsRegistry.PALLADIUM_TRIDENT, "Palladium Trident");
        translationBuilder.add(WeaponsRegistry.PALLADIUM_WARHAMMER, "Palladium Warhammer");

        translationBuilder.add(ToolsRegistry.PLATINUM_PICKAXE, "Platinum Pickaxe");
        translationBuilder.add(ToolsRegistry.PLATINUM_AXE, "Platinum Axe");
        translationBuilder.add(ToolsRegistry.PLATINUM_SHOVEL, "Platinum Shovel");
        translationBuilder.add(ToolsRegistry.PLATINUM_HOE, "Platinum Hoe");
        translationBuilder.add(WeaponsRegistry.PLATINUM_BATTLEAXE, "Platinum Battleaxe");
        // translationBuilder.add(WeaponsRegistry.PLATINUM_CAESTUS, "Platinum Caestus");
        translationBuilder.add(WeaponsRegistry.PLATINUM_CLAYMORE, "Platinum Claymore");
        translationBuilder.add(WeaponsRegistry.PLATINUM_DAGGER, "Platinum Dagger");
        translationBuilder.add(WeaponsRegistry.PLATINUM_FALCHION, "Platinum Falchion");
        translationBuilder.add(WeaponsRegistry.PLATINUM_GAUNTLET, "Platinum Gauntlet");
        translationBuilder.add(WeaponsRegistry.PLATINUM_GREATSWORD, "Platinum Greatsword");
        translationBuilder.add(WeaponsRegistry.PLATINUM_GLAIVE, "Platinum Glaive");
        translationBuilder.add(WeaponsRegistry.PLATINUM_HALBERD, "Platinum Halberd");
        translationBuilder.add(WeaponsRegistry.PLATINUM_HANDAXE, "Platinum Handaxe");
        translationBuilder.add(WeaponsRegistry.PLATINUM_LONG_SPEAR, "Platinum Long Spear");
        translationBuilder.add(WeaponsRegistry.PLATINUM_LONGSWORD, "Platinum Longsword");
        translationBuilder.add(WeaponsRegistry.PLATINUM_MACE, "Platinum Mace");
        translationBuilder.add(WeaponsRegistry.PLATINUM_PIKE, "Platinum Pike");
        translationBuilder.add(WeaponsRegistry.PLATINUM_QUARTERSTAFF, "Platinum Quarterstaff");
        translationBuilder.add(WeaponsRegistry.PLATINUM_RAPIER, "Platinum Rapier");
        translationBuilder.add(WeaponsRegistry.PLATINUM_SCIMITAR, "Platinum Scimitar");
        translationBuilder.add(WeaponsRegistry.PLATINUM_SCYTHE, "Platinum Scythe");
        translationBuilder.add(WeaponsRegistry.PLATINUM_SPEAR, "Platinum Spear");
        translationBuilder.add(WeaponsRegistry.PLATINUM_SWORD, "Platinum Sword");
        translationBuilder.add(WeaponsRegistry.PLATINUM_SICKLE, "Platinum Sickle");
        translationBuilder.add(WeaponsRegistry.PLATINUM_TRIDENT, "Platinum Trident");
        translationBuilder.add(WeaponsRegistry.PLATINUM_WARHAMMER, "Platinum Warhammer");

        translationBuilder.add(ToolsRegistry.SHADOW_ADAMANTINE_PICKAXE, "Shadow Adamantine Pickaxe");
        translationBuilder.add(ToolsRegistry.SHADOW_ADAMANTINE_AXE, "Shadow Adamantine Axe");
        translationBuilder.add(ToolsRegistry.SHADOW_ADAMANTINE_SHOVEL, "Shadow Adamantine Shovel");
        translationBuilder.add(ToolsRegistry.SHADOW_ADAMANTINE_HOE, "Shadow Adamantine Hoe");
        translationBuilder.add(WeaponsRegistry.SHADOW_ADAMANTINE_BATTLEAXE, "Shadow Adamantine Battleaxe");
        // translationBuilder.add(WeaponsRegistry.SHADOW_ADAMANTINE_CAESTUS, "Shadow Adamantine Caestus");
        translationBuilder.add(WeaponsRegistry.SHADOW_ADAMANTINE_CLAYMORE, "Shadow Adamantine Claymore");
        translationBuilder.add(WeaponsRegistry.SHADOW_ADAMANTINE_DAGGER, "Shadow Adamantine Dagger");
        translationBuilder.add(WeaponsRegistry.SHADOW_ADAMANTINE_FALCHION, "Shadow Adamantine Falchion");
        translationBuilder.add(WeaponsRegistry.SHADOW_ADAMANTINE_GAUNTLET, "Shadow Adamantine Gauntlet");
        translationBuilder.add(WeaponsRegistry.SHADOW_ADAMANTINE_GREATSWORD, "Shadow Adamantine Greatsword");
        translationBuilder.add(WeaponsRegistry.SHADOW_ADAMANTINE_GLAIVE, "Shadow Adamantine Glaive");
        translationBuilder.add(WeaponsRegistry.SHADOW_ADAMANTINE_HALBERD, "Shadow Adamantine Halberd");
        translationBuilder.add(WeaponsRegistry.SHADOW_ADAMANTINE_HANDAXE, "Shadow Adamantine Handaxe");
        translationBuilder.add(WeaponsRegistry.SHADOW_ADAMANTINE_LONG_SPEAR, "Shadow Adamantine Long Spear");
        translationBuilder.add(WeaponsRegistry.SHADOW_ADAMANTINE_LONGSWORD, "Shadow Adamantine Longsword");
        translationBuilder.add(WeaponsRegistry.SHADOW_ADAMANTINE_MACE, "Shadow Adamantine Mace");
        translationBuilder.add(WeaponsRegistry.SHADOW_ADAMANTINE_PIKE, "Shadow Adamantine Pike");
        translationBuilder.add(WeaponsRegistry.SHADOW_ADAMANTINE_QUARTERSTAFF, "Shadow Adamantine Quarterstaff");
        translationBuilder.add(WeaponsRegistry.SHADOW_ADAMANTINE_RAPIER, "Shadow Adamantine Rapier");
        translationBuilder.add(WeaponsRegistry.SHADOW_ADAMANTINE_SCIMITAR, "Shadow Adamantine Scimitar");
        translationBuilder.add(WeaponsRegistry.SHADOW_ADAMANTINE_SCYTHE, "Shadow Adamantine Scythe");
        translationBuilder.add(WeaponsRegistry.SHADOW_ADAMANTINE_SPEAR, "Shadow Adamantine Spear");
        translationBuilder.add(WeaponsRegistry.SHADOW_ADAMANTINE_SWORD, "Shadow Adamantine Sword");
        translationBuilder.add(WeaponsRegistry.SHADOW_ADAMANTINE_SICKLE, "Shadow Adamantine Sickle");
        translationBuilder.add(WeaponsRegistry.SHADOW_ADAMANTINE_TRIDENT, "Shadow Adamantine Trident");
        translationBuilder.add(WeaponsRegistry.SHADOW_ADAMANTINE_WARHAMMER, "Shadow Adamantine Warhammer");

        translationBuilder.add(ToolsRegistry.SHADOW_ADAMANTINE_DRAGON_BONE_PICKAXE, "Shadow Adamantine Dragon Bone Pickaxe");
        translationBuilder.add(ToolsRegistry.SHADOW_ADAMANTINE_DRAGON_BONE_AXE, "Shadow Adamantine Dragon Bone Axe");
        translationBuilder.add(ToolsRegistry.SHADOW_ADAMANTINE_DRAGON_BONE_SHOVEL, "Shadow Adamantine Dragon Bone Shovel");
        translationBuilder.add(ToolsRegistry.SHADOW_ADAMANTINE_DRAGON_BONE_HOE, "Shadow Adamantine Dragon Bone Hoe");
        translationBuilder.add(WeaponsRegistry.SHADOW_ADAMANTINE_DRAGON_BONE_BATTLEAXE, "Shadow Adamantine Dragon Bone Battleaxe");
        translationBuilder.add(WeaponsRegistry.SHADOW_ADAMANTINE_DRAGON_BONE_CAESTUS, "Shadow Adamantine Dragon Bone Caestus");
        // translationBuilder.add(WeaponsRegistry.SHADOW_ADAMANTINE_DRAGON_BONE_CLAYMORE, "Shadow Adamantine Dragon Bone Claymore");
        // translationBuilder.add(WeaponsRegistry.SHADOW_ADAMANTINE_DRAGON_BONE_DAGGER, "Shadow Adamantine Dragon Bone Dagger");
        translationBuilder.add(WeaponsRegistry.SHADOW_ADAMANTINE_DRAGON_BONE_FALCHION, "Shadow Adamantine Dragon Bone Falchion");
        // translationBuilder.add(WeaponsRegistry.SHADOW_ADAMANTINE_DRAGON_BONE_GAUNTLET, "Shadow Adamantine Dragon Bone Gauntlet");
        translationBuilder.add(WeaponsRegistry.SHADOW_ADAMANTINE_DRAGON_BONE_GREATSWORD, "Shadow Adamantine Dragon Bone Greatsword");
        translationBuilder.add(WeaponsRegistry.SHADOW_ADAMANTINE_DRAGON_BONE_GLAIVE, "Shadow Adamantine Dragon Bone Glaive");
        // translationBuilder.add(WeaponsRegistry.SHADOW_ADAMANTINE_DRAGON_BONE_HALBERD, "Shadow Adamantine Dragon Bone Halberd");
        // translationBuilder.add(WeaponsRegistry.SHADOW_ADAMANTINE_DRAGON_BONE_HANDAXE, "Shadow Adamantine Dragon Bone Handaxe");
        // translationBuilder.add(WeaponsRegistry.SHADOW_ADAMANTINE_DRAGON_BONE_LONG_SPEAR, "Shadow Adamantine Dragon Bone Long Spear");
        // translationBuilder.add(WeaponsRegistry.SHADOW_ADAMANTINE_DRAGON_BONE_LONGSWORD, "Shadow Adamantine Dragon Bone Longsword");
        translationBuilder.add(WeaponsRegistry.SHADOW_ADAMANTINE_DRAGON_BONE_MACE, "Shadow Adamantine Dragon Bone Mace");
        // translationBuilder.add(WeaponsRegistry.SHADOW_ADAMANTINE_DRAGON_BONE_PIKE, "Shadow Adamantine Dragon Bone Pike");
        translationBuilder.add(WeaponsRegistry.SHADOW_ADAMANTINE_DRAGON_BONE_QUARTERSTAFF, "Shadow Adamantine Dragon Bone Quarterstaff");
        translationBuilder.add(WeaponsRegistry.SHADOW_ADAMANTINE_DRAGON_BONE_RAPIER, "Shadow Adamantine Dragon Bone Rapier");
        translationBuilder.add(WeaponsRegistry.SHADOW_ADAMANTINE_DRAGON_BONE_SCIMITAR, "Shadow Adamantine Dragon Bone Scimitar");
        translationBuilder.add(WeaponsRegistry.SHADOW_ADAMANTINE_DRAGON_BONE_SCYTHE, "Shadow Adamantine Dragon Bone Scythe");
        translationBuilder.add(WeaponsRegistry.SHADOW_ADAMANTINE_DRAGON_BONE_SPEAR, "Shadow Adamantine Dragon Bone Spear");
        translationBuilder.add(WeaponsRegistry.SHADOW_ADAMANTINE_DRAGON_BONE_SWORD, "Shadow Adamantine Dragon Bone Sword");
        translationBuilder.add(WeaponsRegistry.SHADOW_ADAMANTINE_DRAGON_BONE_SICKLE, "Shadow Adamantine Dragon Bone Sickle");
        // translationBuilder.add(WeaponsRegistry.SHADOW_ADAMANTINE_DRAGON_BONE_TRIDENT, "Shadow Adamantine Dragon Bone Trident");
        translationBuilder.add(WeaponsRegistry.SHADOW_ADAMANTINE_DRAGON_BONE_WARHAMMER, "Shadow Adamantine Dragon Bone Warhammer");

        translationBuilder.add(ToolsRegistry.SILVER_PICKAXE, "Silver Pickaxe");
        translationBuilder.add(ToolsRegistry.SILVER_AXE, "Silver Axe");
        translationBuilder.add(ToolsRegistry.SILVER_SHOVEL, "Silver Shovel");
        translationBuilder.add(ToolsRegistry.SILVER_HOE, "Silver Hoe");
        translationBuilder.add(WeaponsRegistry.SILVER_BATTLEAXE, "Silver Battleaxe");
        // translationBuilder.add(WeaponsRegistry.SILVER_CAESTUS, "Silver Caestus");
        translationBuilder.add(WeaponsRegistry.SILVER_CLAYMORE, "Silver Claymore");
        translationBuilder.add(WeaponsRegistry.SILVER_DAGGER, "Silver Dagger");
        translationBuilder.add(WeaponsRegistry.SILVER_FALCHION, "Silver Falchion");
        translationBuilder.add(WeaponsRegistry.SILVER_GAUNTLET, "Silver Gauntlet");
        translationBuilder.add(WeaponsRegistry.SILVER_GREATSWORD, "Silver Greatsword");
        translationBuilder.add(WeaponsRegistry.SILVER_GLAIVE, "Silver Glaive");
        translationBuilder.add(WeaponsRegistry.SILVER_HALBERD, "Silver Halberd");
        translationBuilder.add(WeaponsRegistry.SILVER_HANDAXE, "Silver Handaxe");
        translationBuilder.add(WeaponsRegistry.SILVER_LONG_SPEAR, "Silver Long Spear");
        translationBuilder.add(WeaponsRegistry.SILVER_LONGSWORD, "Silver Longsword");
        translationBuilder.add(WeaponsRegistry.SILVER_MACE, "Silver Mace");
        translationBuilder.add(WeaponsRegistry.SILVER_PIKE, "Silver Pike");
        translationBuilder.add(WeaponsRegistry.SILVER_QUARTERSTAFF, "Silver Quarterstaff");
        translationBuilder.add(WeaponsRegistry.SILVER_RAPIER, "Silver Rapier");
        translationBuilder.add(WeaponsRegistry.SILVER_SCIMITAR, "Silver Scimitar");
        translationBuilder.add(WeaponsRegistry.SILVER_SCYTHE, "Silver Scythe");
        translationBuilder.add(WeaponsRegistry.SILVER_SPEAR, "Silver Spear");
        translationBuilder.add(WeaponsRegistry.SILVER_SWORD, "Silver Sword");
        translationBuilder.add(WeaponsRegistry.SILVER_SICKLE, "Silver Sickle");
        translationBuilder.add(WeaponsRegistry.SILVER_TRIDENT, "Silver Trident");
        translationBuilder.add(WeaponsRegistry.SILVER_WARHAMMER, "Silver Warhammer");

        translationBuilder.add(ToolsRegistry.STEEL_PICKAXE, "Steel Pickaxe");
        translationBuilder.add(ToolsRegistry.STEEL_AXE, "Steel Axe");
        translationBuilder.add(ToolsRegistry.STEEL_SHOVEL, "Steel Shovel");
        translationBuilder.add(ToolsRegistry.STEEL_HOE, "Steel Hoe");
        translationBuilder.add(WeaponsRegistry.STEEL_BATTLEAXE, "Steel Battleaxe");
        // translationBuilder.add(WeaponsRegistry.STEEL_CAESTUS, "Steel Caestus");
        translationBuilder.add(WeaponsRegistry.STEEL_CLAYMORE, "Steel Claymore");
        translationBuilder.add(WeaponsRegistry.STEEL_DAGGER, "Steel Dagger");
        translationBuilder.add(WeaponsRegistry.STEEL_FALCHION, "Steel Falchion");
        translationBuilder.add(WeaponsRegistry.STEEL_GAUNTLET, "Steel Gauntlet");
        translationBuilder.add(WeaponsRegistry.STEEL_GREATSWORD, "Steel Greatsword");
        translationBuilder.add(WeaponsRegistry.STEEL_GLAIVE, "Steel Glaive");
        translationBuilder.add(WeaponsRegistry.STEEL_HALBERD, "Steel Halberd");
        translationBuilder.add(WeaponsRegistry.STEEL_HANDAXE, "Steel Handaxe");
        translationBuilder.add(WeaponsRegistry.STEEL_LONG_SPEAR, "Steel Long Spear");
        translationBuilder.add(WeaponsRegistry.STEEL_LONGSWORD, "Steel Longsword");
        translationBuilder.add(WeaponsRegistry.STEEL_MACE, "Steel Mace");
        translationBuilder.add(WeaponsRegistry.STEEL_PIKE, "Steel Pike");
        translationBuilder.add(WeaponsRegistry.STEEL_QUARTERSTAFF, "Steel Quarterstaff");
        translationBuilder.add(WeaponsRegistry.STEEL_RAPIER, "Steel Rapier");
        translationBuilder.add(WeaponsRegistry.STEEL_SCIMITAR, "Steel Scimitar");
        translationBuilder.add(WeaponsRegistry.STEEL_SCYTHE, "Steel Scythe");
        translationBuilder.add(WeaponsRegistry.STEEL_SPEAR, "Steel Spear");
        translationBuilder.add(WeaponsRegistry.STEEL_SWORD, "Steel Sword");
        translationBuilder.add(WeaponsRegistry.STEEL_SICKLE, "Steel Sickle");
        translationBuilder.add(WeaponsRegistry.STEEL_TRIDENT, "Steel Trident");
        translationBuilder.add(WeaponsRegistry.STEEL_WARHAMMER, "Steel Warhammer");

        translationBuilder.add(WeaponsRegistry.STONE_BATTLEAXE, "Stone Battleaxe");
        // translationBuilder.add(WeaponsRegistry.STONE_CAESTUS, "Stone Caestus");
        translationBuilder.add(WeaponsRegistry.STONE_CLAYMORE, "Stone Claymore");
        translationBuilder.add(WeaponsRegistry.STONE_DAGGER, "Stone Dagger");
        translationBuilder.add(WeaponsRegistry.STONE_FALCHION, "Stone Falchion");
        // translationBuilder.add(WeaponsRegistry.STONE_GAUNTLET, "Stone Gauntlet");
        translationBuilder.add(WeaponsRegistry.STONE_GREATSWORD, "Stone Greatsword");
        translationBuilder.add(WeaponsRegistry.STONE_GLAIVE, "Stone Glaive");
        translationBuilder.add(WeaponsRegistry.STONE_HALBERD, "Stone Halberd");
        translationBuilder.add(WeaponsRegistry.STONE_HANDAXE, "Stone Handaxe");
        translationBuilder.add(WeaponsRegistry.STONE_LONG_SPEAR, "Stone Long Spear");
        translationBuilder.add(WeaponsRegistry.STONE_LONGSWORD, "Stone Longsword");
        translationBuilder.add(WeaponsRegistry.STONE_MACE, "Stone Mace");
        translationBuilder.add(WeaponsRegistry.STONE_PIKE, "Stone Pike");
        translationBuilder.add(WeaponsRegistry.STONE_QUARTERSTAFF, "Stone Quarterstaff");
        translationBuilder.add(WeaponsRegistry.STONE_RAPIER, "Stone Rapier");
        translationBuilder.add(WeaponsRegistry.STONE_SCIMITAR, "Stone Scimitar");
        translationBuilder.add(WeaponsRegistry.STONE_SCYTHE, "Stone Scythe");
        translationBuilder.add(WeaponsRegistry.STONE_SPEAR, "Stone Spear");
        translationBuilder.add(WeaponsRegistry.STONE_SICKLE, "Stone Sickle");
        translationBuilder.add(WeaponsRegistry.STONE_TRIDENT, "Stone Trident");
        translationBuilder.add(WeaponsRegistry.STONE_WARHAMMER, "Stone Warhammer");

        // translationBuilder.add(ToolsRegistry.TITANIUM_PICKAXE, "Titanium Pickaxe");
        // translationBuilder.add(ToolsRegistry.TITANIUM_AXE, "Titanium Axe");
        // translationBuilder.add(ToolsRegistry.TITANIUM_SHOVEL, "Titanium Shovel");
        // translationBuilder.add(ToolsRegistry.TITANIUM_HOE, "Titanium Hoe");
        // translationBuilder.add(WeaponsRegistry.TITANIUM_BATTLEAXE, "Titanium Battleaxe");
        // translationBuilder.add(WeaponsRegistry.TITANIUM_CAESTUS, "Titanium Caestus");
        translationBuilder.add(WeaponsRegistry.TITANIUM_CLAYMORE, "Titanium Claymore");
        // translationBuilder.add(WeaponsRegistry.TITANIUM_DAGGER, "Titanium Dagger");
        // translationBuilder.add(WeaponsRegistry.TITANIUM_FALCHION, "Titanium Falchion");
        // translationBuilder.add(WeaponsRegistry.TITANIUM_GAUNTLET, "Titanium Gauntlet");
        // translationBuilder.add(WeaponsRegistry.TITANIUM_GLAIVE, "Titanium Glaive");
        // translationBuilder.add(WeaponsRegistry.TITANIUM_GREATSWORD, "Titanium Greatsword");
        translationBuilder.add(WeaponsRegistry.TITANIUM_HALBERD, "Titanium Halberd");
        translationBuilder.add(WeaponsRegistry.TITANIUM_HANDAXE, "Titanium Handaxe");
        translationBuilder.add(WeaponsRegistry.TITANIUM_LONG_SPEAR, "Titanium Long Spear");
        translationBuilder.add(WeaponsRegistry.TITANIUM_LONGSWORD, "Titanium Longsword");
        // translationBuilder.add(WeaponsRegistry.TITANIUM_MACE, "Titanium Mace");
        // translationBuilder.add(WeaponsRegistry.TITANIUM_PIKE, "Titanium Pike");
        // translationBuilder.add(WeaponsRegistry.TITANIUM_QUARTERSTAFF, "Titanium Quarterstaff");
        // translationBuilder.add(WeaponsRegistry.TITANIUM_RAPIER, "Titanium Rapier");
        // translationBuilder.add(WeaponsRegistry.TITANIUM_SCIMITAR, "Titanium Scimitar");
        // translationBuilder.add(WeaponsRegistry.TITANIUM_SCYTHE, "Titanium Scythe");
        // translationBuilder.add(WeaponsRegistry.TITANIUM_SPEAR, "Titanium Spear");
        // translationBuilder.add(WeaponsRegistry.TITANIUM_SWORD, "Titanium Sword");
        // translationBuilder.add(WeaponsRegistry.TITANIUM_SICKLE, "Titanium Sickle");
        // translationBuilder.add(WeaponsRegistry.TITANIUM_TRIDENT, "Titanium Trident");
        // translationBuilder.add(WeaponsRegistry.TITANIUM_WARHAMMER, "Titanium Warhammer");

        translationBuilder.add(ToolsRegistry.TUNGSTEN_CARBIDE_PICKAXE, "Tungsten Carbide Pickaxe");
        translationBuilder.add(ToolsRegistry.TUNGSTEN_CARBIDE_AXE, "Tungsten Carbide Axe");
        translationBuilder.add(ToolsRegistry.TUNGSTEN_CARBIDE_SHOVEL, "Tungsten Carbide Shovel");
        translationBuilder.add(ToolsRegistry.TUNGSTEN_CARBIDE_HOE, "Tungsten Carbide Hoe");
        translationBuilder.add(WeaponsRegistry.TUNGSTEN_CARBIDE_BATTLEAXE, "Tungsten Carbide Battleaxe");
        // translationBuilder.add(WeaponsRegistry.TUNGSTEN_CARBIDE_CAESTUS, "Tungsten Carbide Caestus");
        translationBuilder.add(WeaponsRegistry.TUNGSTEN_CARBIDE_CLAYMORE, "Tungsten Carbide Claymore");
        translationBuilder.add(WeaponsRegistry.TUNGSTEN_CARBIDE_DAGGER, "Tungsten Carbide Dagger");
        translationBuilder.add(WeaponsRegistry.TUNGSTEN_CARBIDE_FALCHION, "Tungsten Carbide Falchion");
        translationBuilder.add(WeaponsRegistry.TUNGSTEN_CARBIDE_GAUNTLET, "Tungsten Carbide Gauntlet");
        translationBuilder.add(WeaponsRegistry.TUNGSTEN_CARBIDE_GLAIVE, "Tungsten Carbide Glaive");
        translationBuilder.add(WeaponsRegistry.TUNGSTEN_CARBIDE_GREATSWORD, "Tungsten Carbide Greatsword");
        translationBuilder.add(WeaponsRegistry.TUNGSTEN_CARBIDE_HALBERD, "Tungsten Carbide Halberd");
        translationBuilder.add(WeaponsRegistry.TUNGSTEN_CARBIDE_HANDAXE, "Tungsten Carbide Handaxe");
        translationBuilder.add(WeaponsRegistry.TUNGSTEN_CARBIDE_LONG_SPEAR, "Tungsten Carbide Long Spear");
        translationBuilder.add(WeaponsRegistry.TUNGSTEN_CARBIDE_LONGSWORD, "Tungsten Carbide Longsword");
        translationBuilder.add(WeaponsRegistry.TUNGSTEN_CARBIDE_MACE, "Tungsten Carbide Mace");
        translationBuilder.add(WeaponsRegistry.TUNGSTEN_CARBIDE_PIKE, "Tungsten Carbide Pike");
        // translationBuilder.add(WeaponsRegistry.TUNGSTEN_CARBIDE_QUARTERSTAFF, "Tungsten Carbide Quarterstaff");
        translationBuilder.add(WeaponsRegistry.TUNGSTEN_CARBIDE_RAPIER, "Tungsten Carbide Rapier");
        translationBuilder.add(WeaponsRegistry.TUNGSTEN_CARBIDE_SCIMITAR, "Tungsten Carbide Scimitar");
        translationBuilder.add(WeaponsRegistry.TUNGSTEN_CARBIDE_SCYTHE, "Tungsten Carbide Scythe");
        translationBuilder.add(WeaponsRegistry.TUNGSTEN_CARBIDE_SPEAR, "Tungsten Carbide Spear");
        translationBuilder.add(WeaponsRegistry.TUNGSTEN_CARBIDE_SWORD, "Tungsten Carbide Sword");
        translationBuilder.add(WeaponsRegistry.TUNGSTEN_CARBIDE_SICKLE, "Tungsten Carbide Sickle");
        translationBuilder.add(WeaponsRegistry.TUNGSTEN_CARBIDE_TRIDENT, "Tungsten Carbide Trident");
        translationBuilder.add(WeaponsRegistry.TUNGSTEN_CARBIDE_WARHAMMER, "Tungsten Carbide Warhammer");

        translationBuilder.add(WeaponsRegistry.WOODEN_BATTLEAXE, "Wooden Battleaxe");
        // translationBuilder.add(WeaponsRegistry.WOODEN_CAESTUS, "Wooden Caestus");
        translationBuilder.add(WeaponsRegistry.WOODEN_CLAYMORE, "Wooden Claymore");
        translationBuilder.add(WeaponsRegistry.WOODEN_DAGGER, "Wooden Dagger");
        translationBuilder.add(WeaponsRegistry.WOODEN_FALCHION, "Wooden Falchion");
        // translationBuilder.add(WeaponsRegistry.WOODEN_GAUNTLET, "Wooden Gauntlet");
        translationBuilder.add(WeaponsRegistry.WOODEN_GLAIVE, "Wooden Glaive");
        translationBuilder.add(WeaponsRegistry.WOODEN_GREATSWORD, "Wooden Greatsword");
        translationBuilder.add(WeaponsRegistry.WOODEN_HALBERD, "Wooden Halberd");
        translationBuilder.add(WeaponsRegistry.WOODEN_HANDAXE, "Wooden Handaxe");
        translationBuilder.add(WeaponsRegistry.WOODEN_LONG_SPEAR, "Wooden Long Spear");
        translationBuilder.add(WeaponsRegistry.WOODEN_LONGSWORD, "Wooden Longsword");
        translationBuilder.add(WeaponsRegistry.WOODEN_MACE, "Wooden Mace");
        translationBuilder.add(WeaponsRegistry.WOODEN_PIKE, "Wooden Pike");
        translationBuilder.add(WeaponsRegistry.WOODEN_QUARTERSTAFF, "Wooden Quarterstaff");
        translationBuilder.add(WeaponsRegistry.WOODEN_RAPIER, "Wooden Rapier");
        translationBuilder.add(WeaponsRegistry.WOODEN_SCIMITAR, "Wooden Scimitar");
        translationBuilder.add(WeaponsRegistry.WOODEN_SCYTHE, "Wooden Scythe");
        translationBuilder.add(WeaponsRegistry.WOODEN_SPEAR, "Wooden Spear");
        translationBuilder.add(WeaponsRegistry.WOODEN_SICKLE, "Wooden Sickle");
        translationBuilder.add(WeaponsRegistry.WOODEN_TRIDENT, "Wooden Trident");
        translationBuilder.add(WeaponsRegistry.WOODEN_WARHAMMER, "Wooden Warhammer");
    }
}
