package me.meetmywagon23.dragonshoardwa.datagen;

import me.meetmywagon23.dragonshoardwa.registries.ToolsRegistry;
import me.meetmywagon23.dragonshoardwa.registries.WeaponsRegistry;
import net.fabricmc.fabric.api.datagen.v1.FabricDataOutput;
import net.fabricmc.fabric.api.datagen.v1.provider.FabricTagProvider;
import net.minecraft.registry.RegistryKeys;
import net.minecraft.registry.RegistryWrapper;
import net.minecraft.registry.tag.ItemTags;
import net.minecraft.registry.tag.TagKey;
import net.minecraft.util.Identifier;

import java.util.concurrent.CompletableFuture;

public class DragonsHoardWAItemTagProvider extends FabricTagProvider.ItemTagProvider {
    public DragonsHoardWAItemTagProvider(FabricDataOutput output, CompletableFuture<RegistryWrapper.WrapperLookup> completableFuture) {
        super(output, completableFuture);
    }

    @Override
    protected void configure(RegistryWrapper.WrapperLookup arg) {
        getOrCreateTagBuilder(ItemTags.TOOLS).add(
                // WeaponsRegistry.ADAMANTINE_DRAGON_BONE_TRIDENT,
                WeaponsRegistry.ADAMANTINE_TRIDENT,
                WeaponsRegistry.BONE_TRIDENT,
                WeaponsRegistry.BRONZE_TRIDENT,
                WeaponsRegistry.COLD_IRON_TRIDENT,
                WeaponsRegistry.COPPER_TRIDENT,
                WeaponsRegistry.DARK_STEEL_TRIDENT,
                WeaponsRegistry.DIAMOND_TRIDENT,
                WeaponsRegistry.DRAGON_BONE_TRIDENT,
                WeaponsRegistry.ELVEN_STEEL_TRIDENT,
                WeaponsRegistry.GOLDEN_TRIDENT,
                WeaponsRegistry.INFERNAL_IRON_TRIDENT,
                WeaponsRegistry.IRON_TRIDENT,
                WeaponsRegistry.MITHRIL_TRIDENT,
                WeaponsRegistry.NETHERITE_TRIDENT,
                WeaponsRegistry.PALLADIUM_TRIDENT,
                WeaponsRegistry.PLATINUM_TRIDENT,
                // WeaponsRegistry.SHADOW_ADAMANTINE_DRAGON_BONE_TRIDENT,
                WeaponsRegistry.SHADOW_ADAMANTINE_TRIDENT,
                WeaponsRegistry.SILVER_TRIDENT,
                WeaponsRegistry.STEEL_TRIDENT,
                WeaponsRegistry.STONE_TRIDENT,
                WeaponsRegistry.TUNGSTEN_CARBIDE_TRIDENT,
                WeaponsRegistry.WOODEN_TRIDENT
        );
        getOrCreateTagBuilder(ItemTags.AXES).add(
                ToolsRegistry.ADAMANTINE_DRAGON_BONE_AXE,
                ToolsRegistry.ADAMANTINE_AXE,
                ToolsRegistry.BONE_AXE,
                ToolsRegistry.BRONZE_AXE,
                ToolsRegistry.COLD_IRON_AXE,
                ToolsRegistry.COPPER_AXE,
                ToolsRegistry.DARK_STEEL_AXE,
                ToolsRegistry.DRAGON_BONE_AXE,
                ToolsRegistry.ELVEN_STEEL_AXE,
                ToolsRegistry.INFERNAL_IRON_AXE,
                ToolsRegistry.MITHRIL_AXE,
                ToolsRegistry.PALLADIUM_AXE,
                ToolsRegistry.PLATINUM_AXE,
                ToolsRegistry.SHADOW_ADAMANTINE_DRAGON_BONE_AXE,
                ToolsRegistry.SHADOW_ADAMANTINE_AXE,
                ToolsRegistry.SILVER_AXE,
                ToolsRegistry.STEEL_AXE,
                ToolsRegistry.TUNGSTEN_CARBIDE_AXE,

                WeaponsRegistry.ADAMANTINE_DRAGON_BONE_BATTLEAXE,
                WeaponsRegistry.ADAMANTINE_BATTLEAXE,
                WeaponsRegistry.BONE_BATTLEAXE,
                WeaponsRegistry.BRONZE_BATTLEAXE,
                WeaponsRegistry.COLD_IRON_BATTLEAXE,
                WeaponsRegistry.COPPER_BATTLEAXE,
                WeaponsRegistry.DARK_STEEL_BATTLEAXE,
                WeaponsRegistry.DIAMOND_BATTLEAXE,
                WeaponsRegistry.DRAGON_BONE_BATTLEAXE,
                WeaponsRegistry.ELVEN_STEEL_BATTLEAXE,
                WeaponsRegistry.GOLDEN_BATTLEAXE,
                WeaponsRegistry.INFERNAL_IRON_BATTLEAXE,
                WeaponsRegistry.IRON_BATTLEAXE,
                WeaponsRegistry.MITHRIL_BATTLEAXE,
                WeaponsRegistry.NETHERITE_BATTLEAXE,
                WeaponsRegistry.PALLADIUM_BATTLEAXE,
                WeaponsRegistry.PLATINUM_BATTLEAXE,
                WeaponsRegistry.SHADOW_ADAMANTINE_DRAGON_BONE_BATTLEAXE,
                WeaponsRegistry.SHADOW_ADAMANTINE_BATTLEAXE,
                WeaponsRegistry.SILVER_BATTLEAXE,
                WeaponsRegistry.STEEL_BATTLEAXE,
                WeaponsRegistry.STONE_BATTLEAXE,
                WeaponsRegistry.TUNGSTEN_CARBIDE_BATTLEAXE,
                WeaponsRegistry.WOODEN_BATTLEAXE

                // WeaponsRegistry.ADAMANTINE_DRAGON_BONE_HANDAXE,
                // WeaponsRegistry.ADAMANTINE_HANDAXE,
                // WeaponsRegistry.BONE_HANDAXE,
                // WeaponsRegistry.BRONZE_HANDAXE,
                // WeaponsRegistry.COLD_IRON_HANDAXE,
                // WeaponsRegistry.COPPER_HANDAXE,
                // WeaponsRegistry.DARK_STEEL_HANDAXE,
                // WeaponsRegistry.DIAMOND_HANDAXE,
                // WeaponsRegistry.DRAGON_BONE_HANDAXE,
                // WeaponsRegistry.ELVEN_STEEL_HANDAXE,
                // WeaponsRegistry.GOLDEN_HANDAXE,
                // WeaponsRegistry.INFERNAL_IRON_HANDAXE,
                // WeaponsRegistry.IRON_HANDAXE,
                // WeaponsRegistry.MITHRIL_HANDAXE,
                // WeaponsRegistry.NETHERITE_HANDAXE,
                // WeaponsRegistry.PALLADIUM_HANDAXE,
                // WeaponsRegistry.PLATINUM_HANDAXE,
                // WeaponsRegistry.SHADOW_ADAMANTINE_DRAGON_BONE_HANDAXE,
                // WeaponsRegistry.SHADOW_ADAMANTINE_HANDAXE,
                // WeaponsRegistry.SILVER_HANDAXE,
                // WeaponsRegistry.STEEL_HANDAXE,
                // WeaponsRegistry.STONE_HANDAXE,
                // WeaponsRegistry.TUNGSTEN_CARBIDE_HANDAXE,
                // WeaponsRegistry.WOODEN_HANDAXE
        );
        getOrCreateTagBuilder(ItemTags.HOES).add(
                ToolsRegistry.ADAMANTINE_DRAGON_BONE_HOE,
                ToolsRegistry.ADAMANTINE_HOE,
                ToolsRegistry.BONE_HOE,
                ToolsRegistry.BRONZE_HOE,
                ToolsRegistry.COLD_IRON_HOE,
                ToolsRegistry.COPPER_HOE,
                ToolsRegistry.DARK_STEEL_HOE,
                ToolsRegistry.DRAGON_BONE_HOE,
                ToolsRegistry.ELVEN_STEEL_HOE,
                ToolsRegistry.INFERNAL_IRON_HOE,
                ToolsRegistry.MITHRIL_HOE,
                ToolsRegistry.PALLADIUM_HOE,
                ToolsRegistry.PLATINUM_HOE,
                ToolsRegistry.SHADOW_ADAMANTINE_DRAGON_BONE_HOE,
                ToolsRegistry.SHADOW_ADAMANTINE_HOE,
                ToolsRegistry.SILVER_HOE,
                ToolsRegistry.STEEL_HOE,
                ToolsRegistry.TUNGSTEN_CARBIDE_HOE
        );
        getOrCreateTagBuilder(ItemTags.PICKAXES).add(
                ToolsRegistry.ADAMANTINE_DRAGON_BONE_PICKAXE,
                ToolsRegistry.ADAMANTINE_PICKAXE,
                ToolsRegistry.BONE_PICKAXE,
                ToolsRegistry.BRONZE_PICKAXE,
                ToolsRegistry.COLD_IRON_PICKAXE,
                ToolsRegistry.COPPER_PICKAXE,
                ToolsRegistry.DARK_STEEL_PICKAXE,
                ToolsRegistry.DRAGON_BONE_PICKAXE,
                ToolsRegistry.ELVEN_STEEL_PICKAXE,
                ToolsRegistry.INFERNAL_IRON_PICKAXE,
                ToolsRegistry.MITHRIL_PICKAXE,
                ToolsRegistry.PALLADIUM_PICKAXE,
                ToolsRegistry.PLATINUM_PICKAXE,
                ToolsRegistry.SHADOW_ADAMANTINE_DRAGON_BONE_PICKAXE,
                ToolsRegistry.SHADOW_ADAMANTINE_PICKAXE,
                ToolsRegistry.SILVER_PICKAXE,
                ToolsRegistry.STEEL_PICKAXE,
                ToolsRegistry.TUNGSTEN_CARBIDE_PICKAXE
        );
        getOrCreateTagBuilder(ItemTags.SHOVELS).add(
                ToolsRegistry.ADAMANTINE_DRAGON_BONE_SHOVEL,
                ToolsRegistry.ADAMANTINE_SHOVEL,
                ToolsRegistry.BONE_SHOVEL,
                ToolsRegistry.BRONZE_SHOVEL,
                ToolsRegistry.COLD_IRON_SHOVEL,
                ToolsRegistry.COPPER_SHOVEL,
                ToolsRegistry.DARK_STEEL_SHOVEL,
                ToolsRegistry.DRAGON_BONE_SHOVEL,
                ToolsRegistry.ELVEN_STEEL_SHOVEL,
                ToolsRegistry.INFERNAL_IRON_SHOVEL,
                ToolsRegistry.MITHRIL_SHOVEL,
                ToolsRegistry.PALLADIUM_SHOVEL,
                ToolsRegistry.PLATINUM_SHOVEL,
                ToolsRegistry.SHADOW_ADAMANTINE_DRAGON_BONE_SHOVEL,
                ToolsRegistry.SHADOW_ADAMANTINE_SHOVEL,
                ToolsRegistry.SILVER_SHOVEL,
                ToolsRegistry.STEEL_SHOVEL,
                ToolsRegistry.TUNGSTEN_CARBIDE_SHOVEL
        );
        getOrCreateTagBuilder(ItemTags.SWORDS).add(
                // WeaponsRegistry.ADAMANTINE_DRAGON_BONE_CLAYMORE,
                WeaponsRegistry.ADAMANTINE_CLAYMORE,
                WeaponsRegistry.BONE_CLAYMORE,
                WeaponsRegistry.BRONZE_CLAYMORE,
                WeaponsRegistry.COLD_IRON_CLAYMORE,
                WeaponsRegistry.COPPER_CLAYMORE,
                WeaponsRegistry.DARK_STEEL_CLAYMORE,
                WeaponsRegistry.DIAMOND_CLAYMORE,
                WeaponsRegistry.DRAGON_BONE_CLAYMORE,
                WeaponsRegistry.ELVEN_STEEL_CLAYMORE,
                WeaponsRegistry.GOLDEN_CLAYMORE,
                WeaponsRegistry.INFERNAL_IRON_CLAYMORE,
                WeaponsRegistry.IRON_CLAYMORE,
                WeaponsRegistry.MITHRIL_CLAYMORE,
                WeaponsRegistry.NETHERITE_CLAYMORE,
                WeaponsRegistry.PALLADIUM_CLAYMORE,
                WeaponsRegistry.PLATINUM_CLAYMORE,
                // WeaponsRegistry.SHADOW_ADAMANTINE_DRAGON_BONE_CLAYMORE,
                WeaponsRegistry.SHADOW_ADAMANTINE_CLAYMORE,
                WeaponsRegistry.SILVER_CLAYMORE,
                WeaponsRegistry.STEEL_CLAYMORE,
                WeaponsRegistry.STONE_CLAYMORE,
                WeaponsRegistry.TUNGSTEN_CARBIDE_CLAYMORE,
                WeaponsRegistry.WOODEN_CLAYMORE,

                // WeaponsRegistry.ADAMANTINE_DRAGON_BONE_DAGGER,
                WeaponsRegistry.ADAMANTINE_DAGGER,
                WeaponsRegistry.BONE_DAGGER,
                // WeaponsRegistry.BRONZE_DAGGER,
                WeaponsRegistry.COLD_IRON_DAGGER,
                WeaponsRegistry.COPPER_DAGGER,
                WeaponsRegistry.DARK_STEEL_DAGGER,
                WeaponsRegistry.DIAMOND_DAGGER,
                WeaponsRegistry.DRAGON_BONE_DAGGER,
                WeaponsRegistry.ELVEN_STEEL_DAGGER,
                WeaponsRegistry.GOLDEN_DAGGER,
                WeaponsRegistry.INFERNAL_IRON_DAGGER,
                WeaponsRegistry.IRON_DAGGER,
                WeaponsRegistry.MITHRIL_DAGGER,
                WeaponsRegistry.NETHERITE_DAGGER,
                WeaponsRegistry.PALLADIUM_DAGGER,
                WeaponsRegistry.PLATINUM_DAGGER,
                // WeaponsRegistry.SHADOW_ADAMANTINE_DRAGON_BONE_DAGGER,
                WeaponsRegistry.SHADOW_ADAMANTINE_DAGGER,
                WeaponsRegistry.SILVER_DAGGER,
                WeaponsRegistry.STEEL_DAGGER,
                WeaponsRegistry.STONE_DAGGER,
                WeaponsRegistry.TUNGSTEN_CARBIDE_DAGGER,
                WeaponsRegistry.WOODEN_DAGGER,

                WeaponsRegistry.ADAMANTINE_DRAGON_BONE_FALCHION,
                WeaponsRegistry.ADAMANTINE_FALCHION,
                WeaponsRegistry.BONE_FALCHION,
                WeaponsRegistry.BRONZE_FALCHION,
                WeaponsRegistry.COLD_IRON_FALCHION,
                WeaponsRegistry.COPPER_FALCHION,
                WeaponsRegistry.DARK_STEEL_FALCHION,
                WeaponsRegistry.DIAMOND_FALCHION,
                WeaponsRegistry.DRAGON_BONE_FALCHION,
                WeaponsRegistry.ELVEN_STEEL_FALCHION,
                WeaponsRegistry.GOLDEN_FALCHION,
                WeaponsRegistry.INFERNAL_IRON_FALCHION,
                WeaponsRegistry.IRON_FALCHION,
                WeaponsRegistry.MITHRIL_FALCHION,
                WeaponsRegistry.NETHERITE_FALCHION,
                WeaponsRegistry.PALLADIUM_FALCHION,
                WeaponsRegistry.PLATINUM_FALCHION,
                WeaponsRegistry.SHADOW_ADAMANTINE_DRAGON_BONE_FALCHION,
                WeaponsRegistry.SHADOW_ADAMANTINE_FALCHION,
                WeaponsRegistry.SILVER_FALCHION,
                WeaponsRegistry.STEEL_FALCHION,
                WeaponsRegistry.STONE_FALCHION,
                WeaponsRegistry.TUNGSTEN_CARBIDE_FALCHION,
                WeaponsRegistry.WOODEN_FALCHION,

                WeaponsRegistry.ADAMANTINE_DRAGON_BONE_GLAIVE,
                WeaponsRegistry.ADAMANTINE_GLAIVE,
                WeaponsRegistry.BONE_GLAIVE,
                WeaponsRegistry.BRONZE_GLAIVE,
                WeaponsRegistry.COLD_IRON_GLAIVE,
                WeaponsRegistry.COPPER_GLAIVE,
                WeaponsRegistry.DARK_STEEL_GLAIVE,
                WeaponsRegistry.DIAMOND_GLAIVE,
                WeaponsRegistry.DRAGON_BONE_GLAIVE,
                WeaponsRegistry.ELVEN_STEEL_GLAIVE,
                WeaponsRegistry.GOLDEN_GLAIVE,
                // WeaponsRegistry.INFERNAL_IRON_GLAIVE,
                WeaponsRegistry.IRON_GLAIVE,
                WeaponsRegistry.MITHRIL_GLAIVE,
                WeaponsRegistry.NETHERITE_GLAIVE,
                WeaponsRegistry.PALLADIUM_GLAIVE,
                WeaponsRegistry.PLATINUM_GLAIVE,
                WeaponsRegistry.SHADOW_ADAMANTINE_DRAGON_BONE_GLAIVE,
                WeaponsRegistry.SHADOW_ADAMANTINE_GLAIVE,
                WeaponsRegistry.SILVER_GLAIVE,
                WeaponsRegistry.STEEL_GLAIVE,
                WeaponsRegistry.STONE_GLAIVE,
                WeaponsRegistry.TUNGSTEN_CARBIDE_GLAIVE,
                WeaponsRegistry.WOODEN_GLAIVE,

                WeaponsRegistry.ADAMANTINE_DRAGON_BONE_GREATSWORD,
                WeaponsRegistry.ADAMANTINE_GREATSWORD,
                WeaponsRegistry.BONE_GREATSWORD,
                WeaponsRegistry.BRONZE_GREATSWORD,
                WeaponsRegistry.COLD_IRON_GREATSWORD,
                WeaponsRegistry.COPPER_GREATSWORD,
                WeaponsRegistry.DARK_STEEL_GREATSWORD,
                WeaponsRegistry.DIAMOND_GREATSWORD,
                WeaponsRegistry.DRAGON_BONE_GREATSWORD,
                WeaponsRegistry.ELVEN_STEEL_GREATSWORD,
                WeaponsRegistry.GOLDEN_GREATSWORD,
                WeaponsRegistry.INFERNAL_IRON_GREATSWORD,
                WeaponsRegistry.IRON_GREATSWORD,
                WeaponsRegistry.MITHRIL_GREATSWORD,
                WeaponsRegistry.NETHERITE_GREATSWORD,
                WeaponsRegistry.PALLADIUM_GREATSWORD,
                WeaponsRegistry.PLATINUM_GREATSWORD,
                WeaponsRegistry.SHADOW_ADAMANTINE_DRAGON_BONE_GREATSWORD,
                WeaponsRegistry.SHADOW_ADAMANTINE_GREATSWORD,
                WeaponsRegistry.SILVER_GREATSWORD,
                WeaponsRegistry.STEEL_GREATSWORD,
                WeaponsRegistry.STONE_GREATSWORD,
                WeaponsRegistry.TUNGSTEN_CARBIDE_GREATSWORD,
                WeaponsRegistry.WOODEN_GREATSWORD,

                // WeaponsRegistry.ADAMANTINE_DRAGON_BONE_HALBERD,
                WeaponsRegistry.ADAMANTINE_HALBERD,
                WeaponsRegistry.BONE_HALBERD,
                WeaponsRegistry.BRONZE_HALBERD,
                WeaponsRegistry.COLD_IRON_HALBERD,
                WeaponsRegistry.COPPER_HALBERD,
                WeaponsRegistry.DARK_STEEL_HALBERD,
                WeaponsRegistry.DIAMOND_HALBERD,
                WeaponsRegistry.DRAGON_BONE_HALBERD,
                WeaponsRegistry.ELVEN_STEEL_HALBERD,
                WeaponsRegistry.GOLDEN_HALBERD,
                WeaponsRegistry.INFERNAL_IRON_HALBERD,
                WeaponsRegistry.IRON_HALBERD,
                WeaponsRegistry.MITHRIL_HALBERD,
                WeaponsRegistry.NETHERITE_HALBERD,
                WeaponsRegistry.PALLADIUM_HALBERD,
                WeaponsRegistry.PLATINUM_HALBERD,
                // WeaponsRegistry.SHADOW_ADAMANTINE_DRAGON_BONE_HALBERD,
                WeaponsRegistry.SHADOW_ADAMANTINE_HALBERD,
                WeaponsRegistry.SILVER_HALBERD,
                WeaponsRegistry.STEEL_HALBERD,
                WeaponsRegistry.STONE_HALBERD,
                WeaponsRegistry.TUNGSTEN_CARBIDE_HALBERD,
                WeaponsRegistry.WOODEN_HALBERD,

                // WeaponsRegistry.ADAMANTINE_DRAGON_BONE_LONGSWORD,
                // WeaponsRegistry.ADAMANTINE_LONGSWORD,
                // WeaponsRegistry.BONE_LONGSWORD,
                // WeaponsRegistry.BRONZE_LONGSWORD,
                // WeaponsRegistry.COLD_IRON_LONGSWORD,
                // WeaponsRegistry.COPPER_LONGSWORD,
                // WeaponsRegistry.DARK_STEEL_LONGSWORD,
                // WeaponsRegistry.DIAMOND_LONGSWORD,
                // WeaponsRegistry.DRAGON_BONE_LONGSWORD,
                // WeaponsRegistry.ELVEN_STEEL_LONGSWORD,
                // WeaponsRegistry.GOLDEN_LONGSWORD,
                // WeaponsRegistry.INFERNAL_IRON_LONGSWORD,
                // WeaponsRegistry.IRON_LONGSWORD,
                // WeaponsRegistry.MITHRIL_LONGSWORD,
                // WeaponsRegistry.NETHERITE_LONGSWORD,
                // WeaponsRegistry.PALLADIUM_LONGSWORD,
                // WeaponsRegistry.PLATINUM_LONGSWORD,
                // WeaponsRegistry.SHADOW_ADAMANTINE_DRAGON_BONE_LONGSWORD,
                // WeaponsRegistry.SHADOW_ADAMANTINE_LONGSWORD,
                // WeaponsRegistry.SILVER_LONGSWORD,
                // WeaponsRegistry.STEEL_LONGSWORD,
                // WeaponsRegistry.STONE_LONGSWORD,
                // WeaponsRegistry.TUNGSTEN_CARBIDE_LONGSWORD,
                // WeaponsRegistry.WOODEN_LONGSWORD,

                WeaponsRegistry.ADAMANTINE_DRAGON_BONE_RAPIER,
                WeaponsRegistry.ADAMANTINE_RAPIER,
                WeaponsRegistry.BONE_RAPIER,
                WeaponsRegistry.BRONZE_RAPIER,
                WeaponsRegistry.COLD_IRON_RAPIER,
                WeaponsRegistry.COPPER_RAPIER,
                WeaponsRegistry.DARK_STEEL_RAPIER,
                WeaponsRegistry.DIAMOND_RAPIER,
                WeaponsRegistry.DRAGON_BONE_RAPIER,
                WeaponsRegistry.ELVEN_STEEL_RAPIER,
                WeaponsRegistry.GOLDEN_RAPIER,
                WeaponsRegistry.INFERNAL_IRON_RAPIER,
                WeaponsRegistry.IRON_RAPIER,
                WeaponsRegistry.MITHRIL_RAPIER,
                WeaponsRegistry.NETHERITE_RAPIER,
                WeaponsRegistry.PALLADIUM_RAPIER,
                WeaponsRegistry.PLATINUM_RAPIER,
                WeaponsRegistry.SHADOW_ADAMANTINE_DRAGON_BONE_RAPIER,
                WeaponsRegistry.SHADOW_ADAMANTINE_RAPIER,
                WeaponsRegistry.SILVER_RAPIER,
                WeaponsRegistry.STEEL_RAPIER,
                WeaponsRegistry.STONE_RAPIER,
                WeaponsRegistry.TUNGSTEN_CARBIDE_RAPIER,
                WeaponsRegistry.WOODEN_RAPIER,

                WeaponsRegistry.ADAMANTINE_DRAGON_BONE_SCIMITAR,
                WeaponsRegistry.ADAMANTINE_SCIMITAR,
                WeaponsRegistry.BONE_SCIMITAR,
                WeaponsRegistry.BRONZE_SCIMITAR,
                WeaponsRegistry.COLD_IRON_SCIMITAR,
                WeaponsRegistry.COPPER_SCIMITAR,
                WeaponsRegistry.DARK_STEEL_SCIMITAR,
                WeaponsRegistry.DIAMOND_SCIMITAR,
                WeaponsRegistry.DRAGON_BONE_SCIMITAR,
                WeaponsRegistry.ELVEN_STEEL_SCIMITAR,
                WeaponsRegistry.GOLDEN_SCIMITAR,
                WeaponsRegistry.INFERNAL_IRON_SCIMITAR,
                WeaponsRegistry.IRON_SCIMITAR,
                WeaponsRegistry.MITHRIL_SCIMITAR,
                WeaponsRegistry.NETHERITE_SCIMITAR,
                WeaponsRegistry.PALLADIUM_SCIMITAR,
                WeaponsRegistry.PLATINUM_SCIMITAR,
                WeaponsRegistry.SHADOW_ADAMANTINE_DRAGON_BONE_SCIMITAR,
                WeaponsRegistry.SHADOW_ADAMANTINE_SCIMITAR,
                WeaponsRegistry.SILVER_SCIMITAR,
                WeaponsRegistry.STEEL_SCIMITAR,
                WeaponsRegistry.STONE_SCIMITAR,
                WeaponsRegistry.TUNGSTEN_CARBIDE_SCIMITAR,
                WeaponsRegistry.WOODEN_SCIMITAR,

                WeaponsRegistry.ADAMANTINE_DRAGON_BONE_SCYTHE,
                WeaponsRegistry.ADAMANTINE_SCYTHE,
                WeaponsRegistry.BONE_SCYTHE,
                WeaponsRegistry.BRONZE_SCYTHE,
                WeaponsRegistry.COLD_IRON_SCYTHE,
                WeaponsRegistry.COPPER_SCYTHE,
                WeaponsRegistry.DARK_STEEL_SCYTHE,
                WeaponsRegistry.DIAMOND_SCYTHE,
                WeaponsRegistry.DRAGON_BONE_SCYTHE,
                WeaponsRegistry.ELVEN_STEEL_SCYTHE,
                WeaponsRegistry.GOLDEN_SCYTHE,
                WeaponsRegistry.INFERNAL_IRON_SCYTHE,
                WeaponsRegistry.IRON_SCYTHE,
                WeaponsRegistry.MITHRIL_SCYTHE,
                WeaponsRegistry.NETHERITE_SCYTHE,
                WeaponsRegistry.PALLADIUM_SCYTHE,
                WeaponsRegistry.PLATINUM_SCYTHE,
                WeaponsRegistry.SHADOW_ADAMANTINE_DRAGON_BONE_SCYTHE,
                WeaponsRegistry.SHADOW_ADAMANTINE_SCYTHE,
                WeaponsRegistry.SILVER_SCYTHE,
                WeaponsRegistry.STEEL_SCYTHE,
                WeaponsRegistry.STONE_SCYTHE,
                WeaponsRegistry.TUNGSTEN_CARBIDE_SCYTHE,
                WeaponsRegistry.WOODEN_SCYTHE,

                WeaponsRegistry.ADAMANTINE_DRAGON_BONE_SICKLE,
                WeaponsRegistry.ADAMANTINE_SICKLE,
                WeaponsRegistry.BONE_SICKLE,
                WeaponsRegistry.BRONZE_SICKLE,
                WeaponsRegistry.COLD_IRON_SICKLE,
                WeaponsRegistry.COPPER_SICKLE,
                WeaponsRegistry.DARK_STEEL_SICKLE,
                WeaponsRegistry.DIAMOND_SICKLE,
                WeaponsRegistry.DRAGON_BONE_SICKLE,
                WeaponsRegistry.ELVEN_STEEL_SICKLE,
                WeaponsRegistry.GOLDEN_SICKLE,
                WeaponsRegistry.INFERNAL_IRON_SICKLE,
                WeaponsRegistry.IRON_SICKLE,
                WeaponsRegistry.MITHRIL_SICKLE,
                WeaponsRegistry.NETHERITE_SICKLE,
                WeaponsRegistry.PALLADIUM_SICKLE,
                WeaponsRegistry.PLATINUM_SICKLE,
                WeaponsRegistry.SHADOW_ADAMANTINE_DRAGON_BONE_SICKLE,
                WeaponsRegistry.SHADOW_ADAMANTINE_SICKLE,
                WeaponsRegistry.SILVER_SICKLE,
                WeaponsRegistry.STEEL_SICKLE,
                WeaponsRegistry.STONE_SICKLE,
                WeaponsRegistry.TUNGSTEN_CARBIDE_SICKLE,
                WeaponsRegistry.WOODEN_SICKLE
        );
        getOrCreateTagBuilder(TagKey.of(RegistryKeys.ITEM, new Identifier("c", "battleaxes"))).add(
                WeaponsRegistry.ADAMANTINE_DRAGON_BONE_BATTLEAXE,
                WeaponsRegistry.ADAMANTINE_BATTLEAXE,
                WeaponsRegistry.BONE_BATTLEAXE,
                WeaponsRegistry.BRONZE_BATTLEAXE,
                WeaponsRegistry.COLD_IRON_BATTLEAXE,
                WeaponsRegistry.COPPER_BATTLEAXE,
                WeaponsRegistry.DARK_STEEL_BATTLEAXE,
                WeaponsRegistry.DIAMOND_BATTLEAXE,
                WeaponsRegistry.DRAGON_BONE_BATTLEAXE,
                WeaponsRegistry.ELVEN_STEEL_BATTLEAXE,
                WeaponsRegistry.GOLDEN_BATTLEAXE,
                WeaponsRegistry.INFERNAL_IRON_BATTLEAXE,
                WeaponsRegistry.IRON_BATTLEAXE,
                WeaponsRegistry.MITHRIL_BATTLEAXE,
                WeaponsRegistry.NETHERITE_BATTLEAXE,
                WeaponsRegistry.PALLADIUM_BATTLEAXE,
                WeaponsRegistry.PLATINUM_BATTLEAXE,
                WeaponsRegistry.SHADOW_ADAMANTINE_DRAGON_BONE_BATTLEAXE,
                WeaponsRegistry.SHADOW_ADAMANTINE_BATTLEAXE,
                WeaponsRegistry.SILVER_BATTLEAXE,
                WeaponsRegistry.STEEL_BATTLEAXE,
                WeaponsRegistry.STONE_BATTLEAXE,
                WeaponsRegistry.TUNGSTEN_CARBIDE_BATTLEAXE,
                WeaponsRegistry.WOODEN_BATTLEAXE
        );
        getOrCreateTagBuilder(TagKey.of(RegistryKeys.ITEM, new Identifier("c", "caesti"))).add(
                WeaponsRegistry.ADAMANTINE_DRAGON_BONE_CAESTUS,
                // WeaponsRegistry.ADAMANTINE_CAESTUS,
                // WeaponsRegistry.BONE_CAESTUS,
                // WeaponsRegistry.BRONZE_CAESTUS,
                // WeaponsRegistry.COLD_IRON_CAESTUS,
                // WeaponsRegistry.COPPER_CAESTUS,
                // WeaponsRegistry.DARK_STEEL_CAESTUS,
                // WeaponsRegistry.DIAMOND_CAESTUS,
                // WeaponsRegistry.DRAGON_BONE_CAESTUS,
                WeaponsRegistry.DRAGON_SCALE_CAESTUS,
                // WeaponsRegistry.ELVEN_STEEL_CAESTUS,
                // WeaponsRegistry.GOLDEN_CAESTUS,
                // WeaponsRegistry.INFERNAL_IRON_CAESTUS,
                // WeaponsRegistry.IRON_CAESTUS,
                WeaponsRegistry.LEATHER_CAESTUS,
                // WeaponsRegistry.MITHRIL_CAESTUS,
                // WeaponsRegistry.NETHERITE_CAESTUS,
                // WeaponsRegistry.PALLADIUM_CAESTUS,
                // WeaponsRegistry.PLATINUM_CAESTUS,
                WeaponsRegistry.SHADOW_ADAMANTINE_DRAGON_BONE_CAESTUS//,
                // WeaponsRegistry.SHADOW_ADAMANTINE_CAESTUS,
                // WeaponsRegistry.SILVER_CAESTUS,
                // WeaponsRegistry.STEEL_CAESTUS,
                // WeaponsRegistry.STONE_CAESTUS,
                // WeaponsRegistry.TUNGSTEN_CARBIDE_CAESTUS,
                // WeaponsRegistry.WOODEN_CAESTUS
        );
        getOrCreateTagBuilder(TagKey.of(RegistryKeys.ITEM, new Identifier("c", "claymores"))).add(
                // WeaponsRegistry.ADAMANTINE_DRAGON_BONE_CLAYMORE,
                WeaponsRegistry.ADAMANTINE_CLAYMORE,
                WeaponsRegistry.BONE_CLAYMORE,
                WeaponsRegistry.BRONZE_CLAYMORE,
                WeaponsRegistry.COLD_IRON_CLAYMORE,
                WeaponsRegistry.COPPER_CLAYMORE,
                WeaponsRegistry.DARK_STEEL_CLAYMORE,
                WeaponsRegistry.DIAMOND_CLAYMORE,
                WeaponsRegistry.DRAGON_BONE_CLAYMORE,
                WeaponsRegistry.ELVEN_STEEL_CLAYMORE,
                WeaponsRegistry.GOLDEN_CLAYMORE,
                WeaponsRegistry.INFERNAL_IRON_CLAYMORE,
                WeaponsRegistry.IRON_CLAYMORE,
                WeaponsRegistry.MITHRIL_CLAYMORE,
                WeaponsRegistry.NETHERITE_CLAYMORE,
                WeaponsRegistry.PALLADIUM_CLAYMORE,
                WeaponsRegistry.PLATINUM_CLAYMORE,
                // WeaponsRegistry.SHADOW_ADAMANTINE_DRAGON_BONE_CLAYMORE,
                WeaponsRegistry.SHADOW_ADAMANTINE_CLAYMORE,
                WeaponsRegistry.SILVER_CLAYMORE,
                WeaponsRegistry.STEEL_CLAYMORE,
                WeaponsRegistry.STONE_CLAYMORE,
                WeaponsRegistry.TUNGSTEN_CARBIDE_CLAYMORE,
                WeaponsRegistry.WOODEN_CLAYMORE
        );
        getOrCreateTagBuilder(TagKey.of(RegistryKeys.ITEM, new Identifier("c", "daggers"))).add(
                // WeaponsRegistry.ADAMANTINE_DRAGON_BONE_DAGGER,
                WeaponsRegistry.ADAMANTINE_DAGGER,
                WeaponsRegistry.BONE_DAGGER,
                // WeaponsRegistry.BRONZE_DAGGER,
                WeaponsRegistry.COLD_IRON_DAGGER,
                WeaponsRegistry.COPPER_DAGGER,
                WeaponsRegistry.DARK_STEEL_DAGGER,
                WeaponsRegistry.DIAMOND_DAGGER,
                WeaponsRegistry.DRAGON_BONE_DAGGER,
                WeaponsRegistry.ELVEN_STEEL_DAGGER,
                WeaponsRegistry.GOLDEN_DAGGER,
                WeaponsRegistry.INFERNAL_IRON_DAGGER,
                WeaponsRegistry.IRON_DAGGER,
                WeaponsRegistry.MITHRIL_DAGGER,
                WeaponsRegistry.NETHERITE_DAGGER,
                WeaponsRegistry.PALLADIUM_DAGGER,
                WeaponsRegistry.PLATINUM_DAGGER,
                // WeaponsRegistry.SHADOW_ADAMANTINE_DRAGON_BONE_DAGGER,
                WeaponsRegistry.SHADOW_ADAMANTINE_DAGGER,
                WeaponsRegistry.SILVER_DAGGER,
                WeaponsRegistry.STEEL_DAGGER,
                WeaponsRegistry.STONE_DAGGER,
                WeaponsRegistry.TUNGSTEN_CARBIDE_DAGGER,
                WeaponsRegistry.WOODEN_DAGGER
        );
        getOrCreateTagBuilder(TagKey.of(RegistryKeys.ITEM, new Identifier("c", "falchions"))).add(
                WeaponsRegistry.ADAMANTINE_DRAGON_BONE_FALCHION,
                WeaponsRegistry.ADAMANTINE_FALCHION,
                WeaponsRegistry.BONE_FALCHION,
                WeaponsRegistry.BRONZE_FALCHION,
                WeaponsRegistry.COLD_IRON_FALCHION,
                WeaponsRegistry.COPPER_FALCHION,
                WeaponsRegistry.DARK_STEEL_FALCHION,
                WeaponsRegistry.DIAMOND_FALCHION,
                WeaponsRegistry.DRAGON_BONE_FALCHION,
                WeaponsRegistry.ELVEN_STEEL_FALCHION,
                WeaponsRegistry.GOLDEN_FALCHION,
                WeaponsRegistry.INFERNAL_IRON_FALCHION,
                WeaponsRegistry.IRON_FALCHION,
                WeaponsRegistry.MITHRIL_FALCHION,
                WeaponsRegistry.NETHERITE_FALCHION,
                WeaponsRegistry.PALLADIUM_FALCHION,
                WeaponsRegistry.PLATINUM_FALCHION,
                WeaponsRegistry.SHADOW_ADAMANTINE_DRAGON_BONE_FALCHION,
                WeaponsRegistry.SHADOW_ADAMANTINE_FALCHION,
                WeaponsRegistry.SILVER_FALCHION,
                WeaponsRegistry.STEEL_FALCHION,
                WeaponsRegistry.STONE_FALCHION,
                WeaponsRegistry.TUNGSTEN_CARBIDE_FALCHION,
                WeaponsRegistry.WOODEN_FALCHION
        );
        getOrCreateTagBuilder(TagKey.of(RegistryKeys.ITEM, new Identifier("c", "gauntlets"))).add(
                // WeaponsRegistry.ADAMANTINE_DRAGON_BONE_GAUNTLET,
                WeaponsRegistry.ADAMANTINE_GAUNTLET,
                // WeaponsRegistry.BONE_GAUNTLET,
                WeaponsRegistry.BRONZE_GAUNTLET,
                WeaponsRegistry.COLD_IRON_GAUNTLET,
                WeaponsRegistry.COPPER_GAUNTLET,
                WeaponsRegistry.DARK_STEEL_GAUNTLET,
                WeaponsRegistry.DIAMOND_GAUNTLET,
                // WeaponsRegistry.DRAGON_BONE_GAUNTLET,
                WeaponsRegistry.ELVEN_STEEL_GAUNTLET,
                WeaponsRegistry.GOLDEN_GAUNTLET,
                WeaponsRegistry.INFERNAL_IRON_GAUNTLET,
                WeaponsRegistry.IRON_GAUNTLET,
                WeaponsRegistry.MITHRIL_GAUNTLET,
                WeaponsRegistry.NETHERITE_GAUNTLET,
                WeaponsRegistry.PALLADIUM_GAUNTLET,
                WeaponsRegistry.PLATINUM_GAUNTLET,
                // WeaponsRegistry.SHADOW_ADAMANTINE_DRAGON_BONE_GAUNTLET,
                WeaponsRegistry.SHADOW_ADAMANTINE_GAUNTLET,
                WeaponsRegistry.SILVER_GAUNTLET,
                WeaponsRegistry.STEEL_GAUNTLET,
                // WeaponsRegistry.STONE_GAUNTLET,
                WeaponsRegistry.TUNGSTEN_CARBIDE_GAUNTLET //,
                // WeaponsRegistry.WOODEN_GAUNTLET
        );
        getOrCreateTagBuilder(TagKey.of(RegistryKeys.ITEM, new Identifier("c", "glavies"))).add(
                WeaponsRegistry.ADAMANTINE_DRAGON_BONE_GLAIVE,
                WeaponsRegistry.ADAMANTINE_GLAIVE,
                WeaponsRegistry.BONE_GLAIVE,
                WeaponsRegistry.BRONZE_GLAIVE,
                WeaponsRegistry.COLD_IRON_GLAIVE,
                WeaponsRegistry.COPPER_GLAIVE,
                WeaponsRegistry.DARK_STEEL_GLAIVE,
                WeaponsRegistry.DIAMOND_GLAIVE,
                WeaponsRegistry.DRAGON_BONE_GLAIVE,
                WeaponsRegistry.ELVEN_STEEL_GLAIVE,
                WeaponsRegistry.GOLDEN_GLAIVE,
                // WeaponsRegistry.INFERNAL_IRON_GLAIVE,
                WeaponsRegistry.IRON_GLAIVE,
                WeaponsRegistry.MITHRIL_GLAIVE,
                WeaponsRegistry.NETHERITE_GLAIVE,
                WeaponsRegistry.PALLADIUM_GLAIVE,
                WeaponsRegistry.PLATINUM_GLAIVE,
                WeaponsRegistry.SHADOW_ADAMANTINE_DRAGON_BONE_GLAIVE,
                WeaponsRegistry.SHADOW_ADAMANTINE_GLAIVE,
                WeaponsRegistry.SILVER_GLAIVE,
                WeaponsRegistry.STEEL_GLAIVE,
                WeaponsRegistry.STONE_GLAIVE,
                WeaponsRegistry.TUNGSTEN_CARBIDE_GLAIVE,
                WeaponsRegistry.WOODEN_GLAIVE
        );
        getOrCreateTagBuilder(TagKey.of(RegistryKeys.ITEM, new Identifier("c", "greatswords"))).add(
                WeaponsRegistry.ADAMANTINE_DRAGON_BONE_GREATSWORD,
                WeaponsRegistry.ADAMANTINE_GREATSWORD,
                WeaponsRegistry.BONE_GREATSWORD,
                WeaponsRegistry.BRONZE_GREATSWORD,
                WeaponsRegistry.COLD_IRON_GREATSWORD,
                WeaponsRegistry.COPPER_GREATSWORD,
                WeaponsRegistry.DARK_STEEL_GREATSWORD,
                WeaponsRegistry.DIAMOND_GREATSWORD,
                WeaponsRegistry.DRAGON_BONE_GREATSWORD,
                WeaponsRegistry.ELVEN_STEEL_GREATSWORD,
                WeaponsRegistry.GOLDEN_GREATSWORD,
                WeaponsRegistry.INFERNAL_IRON_GREATSWORD,
                WeaponsRegistry.IRON_GREATSWORD,
                WeaponsRegistry.MITHRIL_GREATSWORD,
                WeaponsRegistry.NETHERITE_GREATSWORD,
                WeaponsRegistry.PALLADIUM_GREATSWORD,
                WeaponsRegistry.PLATINUM_GREATSWORD,
                WeaponsRegistry.SHADOW_ADAMANTINE_DRAGON_BONE_GREATSWORD,
                WeaponsRegistry.SHADOW_ADAMANTINE_GREATSWORD,
                WeaponsRegistry.SILVER_GREATSWORD,
                WeaponsRegistry.STEEL_GREATSWORD,
                WeaponsRegistry.STONE_GREATSWORD,
                WeaponsRegistry.TUNGSTEN_CARBIDE_GREATSWORD,
                WeaponsRegistry.WOODEN_GREATSWORD
        );
        getOrCreateTagBuilder(TagKey.of(RegistryKeys.ITEM, new Identifier("c", "halberds"))).add(
                // WeaponsRegistry.ADAMANTINE_DRAGON_BONE_HALBERD,
                WeaponsRegistry.ADAMANTINE_HALBERD,
                WeaponsRegistry.BONE_HALBERD,
                WeaponsRegistry.BRONZE_HALBERD,
                WeaponsRegistry.COLD_IRON_HALBERD,
                WeaponsRegistry.COPPER_HALBERD,
                WeaponsRegistry.DARK_STEEL_HALBERD,
                WeaponsRegistry.DIAMOND_HALBERD,
                WeaponsRegistry.DRAGON_BONE_HALBERD,
                WeaponsRegistry.ELVEN_STEEL_HALBERD,
                WeaponsRegistry.GOLDEN_HALBERD,
                WeaponsRegistry.INFERNAL_IRON_HALBERD,
                WeaponsRegistry.IRON_HALBERD,
                WeaponsRegistry.MITHRIL_HALBERD,
                WeaponsRegistry.NETHERITE_HALBERD,
                WeaponsRegistry.PALLADIUM_HALBERD,
                WeaponsRegistry.PLATINUM_HALBERD,
                // WeaponsRegistry.SHADOW_ADAMANTINE_DRAGON_BONE_HALBERD,
                WeaponsRegistry.SHADOW_ADAMANTINE_HALBERD,
                WeaponsRegistry.SILVER_HALBERD,
                WeaponsRegistry.STEEL_HALBERD,
                WeaponsRegistry.STONE_HALBERD,
                WeaponsRegistry.TUNGSTEN_CARBIDE_HALBERD,
                WeaponsRegistry.WOODEN_HALBERD
        );
        //getOrCreateTagBuilder(TagKey.of(RegistryKeys.ITEM, new Identifier("c", "handaxes"))).add(
        //        // WeaponsRegistry.ADAMANTINE_DRAGON_BONE_HANDAXE,
        //        WeaponsRegistry.ADAMANTINE_HANDAXE,
        //        WeaponsRegistry.BONE_HANDAXE,
        //        WeaponsRegistry.BRONZE_HANDAXE,
        //        WeaponsRegistry.COLD_IRON_HANDAXE,
        //        WeaponsRegistry.COPPER_HANDAXE,
        //        WeaponsRegistry.DARK_STEEL_HANDAXE,
        //        WeaponsRegistry.DIAMOND_HANDAXE,
        //        WeaponsRegistry.DRAGON_BONE_HANDAXE,
        //        WeaponsRegistry.ELVEN_STEEL_HANDAXE,
        //        WeaponsRegistry.GOLDEN_HANDAXE,
        //        WeaponsRegistry.INFERNAL_IRON_HANDAXE,
        //        WeaponsRegistry.IRON_HANDAXE,
        //        WeaponsRegistry.MITHRIL_HANDAXE,
        //        WeaponsRegistry.NETHERITE_HANDAXE,
        //        WeaponsRegistry.PALLADIUM_HANDAXE,
        //        WeaponsRegistry.PLATINUM_HANDAXE,
        //        // WeaponsRegistry.SHADOW_ADAMANTINE_DRAGON_BONE_HANDAXE,
        //        WeaponsRegistry.SHADOW_ADAMANTINE_HANDAXE,
        //        WeaponsRegistry.SILVER_HANDAXE,
        //        WeaponsRegistry.STEEL_HANDAXE,
        //        WeaponsRegistry.STONE_HANDAXE,
        //        WeaponsRegistry.TUNGSTEN_CARBIDE_HANDAXE,
        //        WeaponsRegistry.WOODEN_HANDAXE
        //);
        getOrCreateTagBuilder(TagKey.of(RegistryKeys.ITEM, new Identifier("c", "long_spears"))).add(
                // WeaponsRegistry.ADAMANTINE_DRAGON_BONE_LONG_SPEAR,
                WeaponsRegistry.ADAMANTINE_LONG_SPEAR,
                WeaponsRegistry.BONE_LONG_SPEAR,
                WeaponsRegistry.BRONZE_LONG_SPEAR,
                WeaponsRegistry.COLD_IRON_LONG_SPEAR,
                WeaponsRegistry.COPPER_LONG_SPEAR,
                WeaponsRegistry.DARK_STEEL_LONG_SPEAR,
                WeaponsRegistry.DIAMOND_LONG_SPEAR,
                WeaponsRegistry.DRAGON_BONE_LONG_SPEAR,
                WeaponsRegistry.ELVEN_STEEL_LONG_SPEAR,
                WeaponsRegistry.GOLDEN_LONG_SPEAR,
                WeaponsRegistry.INFERNAL_IRON_LONG_SPEAR,
                WeaponsRegistry.IRON_LONG_SPEAR,
                WeaponsRegistry.MITHRIL_LONG_SPEAR,
                WeaponsRegistry.NETHERITE_LONG_SPEAR,
                WeaponsRegistry.PALLADIUM_LONG_SPEAR,
                WeaponsRegistry.PLATINUM_LONG_SPEAR,
                // WeaponsRegistry.SHADOW_ADAMANTINE_DRAGON_BONE_LONG_SPEAR,
                WeaponsRegistry.SHADOW_ADAMANTINE_LONG_SPEAR,
                WeaponsRegistry.SILVER_LONG_SPEAR,
                WeaponsRegistry.STEEL_LONG_SPEAR,
                WeaponsRegistry.STONE_LONG_SPEAR,
                WeaponsRegistry.TUNGSTEN_CARBIDE_LONG_SPEAR,
                WeaponsRegistry.WOODEN_LONG_SPEAR
        );
        // getOrCreateTagBuilder(TagKey.of(RegistryKeys.ITEM, new Identifier("c", "longswords"))).add(
        //         // WeaponsRegistry.ADAMANTINE_DRAGON_BONE_LONGSWORD,
        //         WeaponsRegistry.ADAMANTINE_LONGSWORD,
        //         WeaponsRegistry.BONE_LONGSWORD,
        //         WeaponsRegistry.BRONZE_LONGSWORD,
        //         WeaponsRegistry.COLD_IRON_LONGSWORD,
        //         WeaponsRegistry.COPPER_LONGSWORD,
        //         WeaponsRegistry.DARK_STEEL_LONGSWORD,
        //         WeaponsRegistry.DIAMOND_LONGSWORD,
        //         WeaponsRegistry.DRAGON_BONE_LONGSWORD,
        //         WeaponsRegistry.ELVEN_STEEL_LONGSWORD,
        //         WeaponsRegistry.GOLDEN_LONGSWORD,
        //         WeaponsRegistry.INFERNAL_IRON_LONGSWORD,
        //         WeaponsRegistry.IRON_LONGSWORD,
        //         WeaponsRegistry.MITHRIL_LONGSWORD,
        //         WeaponsRegistry.NETHERITE_LONGSWORD,
        //         WeaponsRegistry.PALLADIUM_LONGSWORD,
        //         WeaponsRegistry.PLATINUM_LONGSWORD,
        //         // WeaponsRegistry.SHADOW_ADAMANTINE_DRAGON_BONE_LONGSWORD,
        //         WeaponsRegistry.SHADOW_ADAMANTINE_LONGSWORD,
        //         WeaponsRegistry.SILVER_LONGSWORD,
        //         WeaponsRegistry.STEEL_LONGSWORD,
        //         WeaponsRegistry.STONE_LONGSWORD,
        //         WeaponsRegistry.TUNGSTEN_CARBIDE_LONGSWORD,
        //         WeaponsRegistry.WOODEN_LONGSWORD
        // );
        getOrCreateTagBuilder(TagKey.of(RegistryKeys.ITEM, new Identifier("c", "maces"))).add(
                WeaponsRegistry.ADAMANTINE_DRAGON_BONE_MACE,
                WeaponsRegistry.ADAMANTINE_MACE,
                WeaponsRegistry.BONE_MACE,
                WeaponsRegistry.BRONZE_MACE,
                WeaponsRegistry.COLD_IRON_MACE,
                WeaponsRegistry.COPPER_MACE,
                WeaponsRegistry.DARK_STEEL_MACE,
                WeaponsRegistry.DIAMOND_MACE,
                WeaponsRegistry.DRAGON_BONE_MACE,
                WeaponsRegistry.ELVEN_STEEL_MACE,
                WeaponsRegistry.GOLDEN_MACE,
                WeaponsRegistry.INFERNAL_IRON_MACE,
                WeaponsRegistry.IRON_MACE,
                WeaponsRegistry.MITHRIL_MACE,
                WeaponsRegistry.NETHERITE_MACE,
                WeaponsRegistry.PALLADIUM_MACE,
                WeaponsRegistry.PLATINUM_MACE,
                WeaponsRegistry.SHADOW_ADAMANTINE_DRAGON_BONE_MACE,
                WeaponsRegistry.SHADOW_ADAMANTINE_MACE,
                WeaponsRegistry.SILVER_MACE,
                WeaponsRegistry.STEEL_MACE,
                WeaponsRegistry.STONE_MACE,
                WeaponsRegistry.TUNGSTEN_CARBIDE_MACE,
                WeaponsRegistry.WOODEN_MACE
        );
        getOrCreateTagBuilder(TagKey.of(RegistryKeys.ITEM, new Identifier("c", "pikes"))).add(
                // WeaponsRegistry.ADAMANTINE_DRAGON_BONE_PIKE,
                WeaponsRegistry.ADAMANTINE_PIKE,
                WeaponsRegistry.BONE_PIKE,
                WeaponsRegistry.BRONZE_PIKE,
                WeaponsRegistry.COLD_IRON_PIKE,
                WeaponsRegistry.COPPER_PIKE,
                WeaponsRegistry.DARK_STEEL_PIKE,
                WeaponsRegistry.DIAMOND_PIKE,
                WeaponsRegistry.DRAGON_BONE_PIKE,
                WeaponsRegistry.ELVEN_STEEL_PIKE,
                WeaponsRegistry.GOLDEN_PIKE,
                WeaponsRegistry.INFERNAL_IRON_PIKE,
                WeaponsRegistry.IRON_PIKE,
                WeaponsRegistry.MITHRIL_PIKE,
                WeaponsRegistry.NETHERITE_PIKE,
                WeaponsRegistry.PALLADIUM_PIKE,
                WeaponsRegistry.PLATINUM_PIKE,
                // WeaponsRegistry.SHADOW_ADAMANTINE_DRAGON_BONE_PIKE,
                WeaponsRegistry.SHADOW_ADAMANTINE_PIKE,
                WeaponsRegistry.SILVER_PIKE,
                WeaponsRegistry.STEEL_PIKE,
                WeaponsRegistry.STONE_PIKE,
                WeaponsRegistry.TUNGSTEN_CARBIDE_PIKE,
                WeaponsRegistry.WOODEN_PIKE
        );
        getOrCreateTagBuilder(TagKey.of(RegistryKeys.ITEM, new Identifier("c", "staves"))).add(
                WeaponsRegistry.ADAMANTINE_DRAGON_BONE_QUARTERSTAFF,
                WeaponsRegistry.ADAMANTINE_QUARTERSTAFF,
                WeaponsRegistry.BONE_QUARTERSTAFF,
                WeaponsRegistry.BRONZE_QUARTERSTAFF,
                WeaponsRegistry.COLD_IRON_QUARTERSTAFF,
                WeaponsRegistry.COPPER_QUARTERSTAFF,
                WeaponsRegistry.DARK_STEEL_QUARTERSTAFF,
                WeaponsRegistry.DIAMOND_QUARTERSTAFF,
                WeaponsRegistry.DRAGON_BONE_QUARTERSTAFF,
                WeaponsRegistry.ELVEN_STEEL_QUARTERSTAFF,
                WeaponsRegistry.GOLDEN_QUARTERSTAFF,
                WeaponsRegistry.INFERNAL_IRON_QUARTERSTAFF,
                WeaponsRegistry.IRON_QUARTERSTAFF,
                WeaponsRegistry.MITHRIL_QUARTERSTAFF,
                WeaponsRegistry.NETHERITE_QUARTERSTAFF,
                WeaponsRegistry.PALLADIUM_QUARTERSTAFF,
                WeaponsRegistry.PLATINUM_QUARTERSTAFF,
                WeaponsRegistry.SHADOW_ADAMANTINE_DRAGON_BONE_QUARTERSTAFF,
                WeaponsRegistry.SHADOW_ADAMANTINE_QUARTERSTAFF,
                WeaponsRegistry.SILVER_QUARTERSTAFF,
                WeaponsRegistry.STEEL_QUARTERSTAFF,
                WeaponsRegistry.STONE_QUARTERSTAFF,
                // WeaponsRegistry.TUNGSTEN_CARBIDE_QUARTERSTAFF,
                WeaponsRegistry.WOODEN_QUARTERSTAFF
        );
        getOrCreateTagBuilder(TagKey.of(RegistryKeys.ITEM, new Identifier("c", "rapiers"))).add(
                WeaponsRegistry.ADAMANTINE_DRAGON_BONE_RAPIER,
                WeaponsRegistry.ADAMANTINE_RAPIER,
                WeaponsRegistry.BONE_RAPIER,
                WeaponsRegistry.BRONZE_RAPIER,
                WeaponsRegistry.COLD_IRON_RAPIER,
                WeaponsRegistry.COPPER_RAPIER,
                WeaponsRegistry.DARK_STEEL_RAPIER,
                WeaponsRegistry.DIAMOND_RAPIER,
                WeaponsRegistry.DRAGON_BONE_RAPIER,
                WeaponsRegistry.ELVEN_STEEL_RAPIER,
                WeaponsRegistry.GOLDEN_RAPIER,
                WeaponsRegistry.INFERNAL_IRON_RAPIER,
                WeaponsRegistry.IRON_RAPIER,
                WeaponsRegistry.MITHRIL_RAPIER,
                WeaponsRegistry.NETHERITE_RAPIER,
                WeaponsRegistry.PALLADIUM_RAPIER,
                WeaponsRegistry.PLATINUM_RAPIER,
                WeaponsRegistry.SHADOW_ADAMANTINE_DRAGON_BONE_RAPIER,
                WeaponsRegistry.SHADOW_ADAMANTINE_RAPIER,
                WeaponsRegistry.SILVER_RAPIER,
                WeaponsRegistry.STEEL_RAPIER,
                WeaponsRegistry.STONE_RAPIER,
                WeaponsRegistry.TUNGSTEN_CARBIDE_RAPIER,
                WeaponsRegistry.WOODEN_RAPIER
        );
        getOrCreateTagBuilder(TagKey.of(RegistryKeys.ITEM, new Identifier("c", "scimitars"))).add(
                WeaponsRegistry.ADAMANTINE_DRAGON_BONE_SCIMITAR,
                WeaponsRegistry.ADAMANTINE_SCIMITAR,
                WeaponsRegistry.BONE_SCIMITAR,
                WeaponsRegistry.BRONZE_SCIMITAR,
                WeaponsRegistry.COLD_IRON_SCIMITAR,
                WeaponsRegistry.COPPER_SCIMITAR,
                WeaponsRegistry.DARK_STEEL_SCIMITAR,
                WeaponsRegistry.DIAMOND_SCIMITAR,
                WeaponsRegistry.DRAGON_BONE_SCIMITAR,
                WeaponsRegistry.ELVEN_STEEL_SCIMITAR,
                WeaponsRegistry.GOLDEN_SCIMITAR,
                WeaponsRegistry.INFERNAL_IRON_SCIMITAR,
                WeaponsRegistry.IRON_SCIMITAR,
                WeaponsRegistry.MITHRIL_SCIMITAR,
                WeaponsRegistry.NETHERITE_SCIMITAR,
                WeaponsRegistry.PALLADIUM_SCIMITAR,
                WeaponsRegistry.PLATINUM_SCIMITAR,
                WeaponsRegistry.SHADOW_ADAMANTINE_DRAGON_BONE_SCIMITAR,
                WeaponsRegistry.SHADOW_ADAMANTINE_SCIMITAR,
                WeaponsRegistry.SILVER_SCIMITAR,
                WeaponsRegistry.STEEL_SCIMITAR,
                WeaponsRegistry.STONE_SCIMITAR,
                WeaponsRegistry.TUNGSTEN_CARBIDE_SCIMITAR,
                WeaponsRegistry.WOODEN_SCIMITAR
        );
        getOrCreateTagBuilder(TagKey.of(RegistryKeys.ITEM, new Identifier("c", "scythes"))).add(
                WeaponsRegistry.ADAMANTINE_DRAGON_BONE_SCYTHE,
                WeaponsRegistry.ADAMANTINE_SCYTHE,
                WeaponsRegistry.BONE_SCYTHE,
                WeaponsRegistry.BRONZE_SCYTHE,
                WeaponsRegistry.COLD_IRON_SCYTHE,
                WeaponsRegistry.COPPER_SCYTHE,
                WeaponsRegistry.DARK_STEEL_SCYTHE,
                WeaponsRegistry.DIAMOND_SCYTHE,
                WeaponsRegistry.DRAGON_BONE_SCYTHE,
                WeaponsRegistry.ELVEN_STEEL_SCYTHE,
                WeaponsRegistry.GOLDEN_SCYTHE,
                WeaponsRegistry.INFERNAL_IRON_SCYTHE,
                WeaponsRegistry.IRON_SCYTHE,
                WeaponsRegistry.MITHRIL_SCYTHE,
                WeaponsRegistry.NETHERITE_SCYTHE,
                WeaponsRegistry.PALLADIUM_SCYTHE,
                WeaponsRegistry.PLATINUM_SCYTHE,
                WeaponsRegistry.SHADOW_ADAMANTINE_DRAGON_BONE_SCYTHE,
                WeaponsRegistry.SHADOW_ADAMANTINE_SCYTHE,
                WeaponsRegistry.SILVER_SCYTHE,
                WeaponsRegistry.STEEL_SCYTHE,
                WeaponsRegistry.STONE_SCYTHE,
                WeaponsRegistry.TUNGSTEN_CARBIDE_SCYTHE,
                WeaponsRegistry.WOODEN_SCYTHE
        );
        getOrCreateTagBuilder(TagKey.of(RegistryKeys.ITEM, new Identifier("c", "spears"))).add(
                WeaponsRegistry.ADAMANTINE_DRAGON_BONE_SPEAR,
                WeaponsRegistry.ADAMANTINE_SPEAR,
                WeaponsRegistry.BONE_SPEAR,
                WeaponsRegistry.BRONZE_SPEAR,
                WeaponsRegistry.COLD_IRON_SPEAR,
                WeaponsRegistry.COPPER_SPEAR,
                WeaponsRegistry.DARK_STEEL_SPEAR,
                WeaponsRegistry.DIAMOND_SPEAR,
                WeaponsRegistry.DRAGON_BONE_SPEAR,
                WeaponsRegistry.ELVEN_STEEL_SPEAR,
                WeaponsRegistry.GOLDEN_SPEAR,
                WeaponsRegistry.INFERNAL_IRON_SPEAR,
                WeaponsRegistry.IRON_SPEAR,
                WeaponsRegistry.MITHRIL_SPEAR,
                WeaponsRegistry.NETHERITE_SPEAR,
                WeaponsRegistry.PALLADIUM_SPEAR,
                WeaponsRegistry.PLATINUM_SPEAR,
                WeaponsRegistry.SHADOW_ADAMANTINE_DRAGON_BONE_SPEAR,
                WeaponsRegistry.SHADOW_ADAMANTINE_SPEAR,
                WeaponsRegistry.SILVER_SPEAR,
                WeaponsRegistry.STEEL_SPEAR,
                WeaponsRegistry.STONE_SPEAR,
                WeaponsRegistry.TUNGSTEN_CARBIDE_SPEAR,
                WeaponsRegistry.WOODEN_SPEAR,

                // WeaponsRegistry.ADAMANTINE_DRAGON_BONE_TRIDENT,
                WeaponsRegistry.ADAMANTINE_TRIDENT,
                WeaponsRegistry.BONE_TRIDENT,
                WeaponsRegistry.BRONZE_TRIDENT,
                WeaponsRegistry.COLD_IRON_TRIDENT,
                WeaponsRegistry.COPPER_TRIDENT,
                WeaponsRegistry.DARK_STEEL_TRIDENT,
                WeaponsRegistry.DIAMOND_TRIDENT,
                WeaponsRegistry.DRAGON_BONE_TRIDENT,
                WeaponsRegistry.ELVEN_STEEL_TRIDENT,
                WeaponsRegistry.GOLDEN_TRIDENT,
                WeaponsRegistry.INFERNAL_IRON_TRIDENT,
                WeaponsRegistry.IRON_TRIDENT,
                WeaponsRegistry.MITHRIL_TRIDENT,
                WeaponsRegistry.NETHERITE_TRIDENT,
                WeaponsRegistry.PALLADIUM_TRIDENT,
                WeaponsRegistry.PLATINUM_TRIDENT,
                // WeaponsRegistry.SHADOW_ADAMANTINE_DRAGON_BONE_TRIDENT,
                WeaponsRegistry.SHADOW_ADAMANTINE_TRIDENT,
                WeaponsRegistry.SILVER_TRIDENT,
                WeaponsRegistry.STEEL_TRIDENT,
                WeaponsRegistry.STONE_TRIDENT,
                WeaponsRegistry.TUNGSTEN_CARBIDE_TRIDENT,
                WeaponsRegistry.WOODEN_TRIDENT
        );
        getOrCreateTagBuilder(TagKey.of(RegistryKeys.ITEM, new Identifier("c", "sickles"))).add(
                WeaponsRegistry.ADAMANTINE_DRAGON_BONE_SICKLE,
                WeaponsRegistry.ADAMANTINE_SICKLE,
                WeaponsRegistry.BONE_SICKLE,
                WeaponsRegistry.BRONZE_SICKLE,
                WeaponsRegistry.COLD_IRON_SICKLE,
                WeaponsRegistry.COPPER_SICKLE,
                WeaponsRegistry.DARK_STEEL_SICKLE,
                WeaponsRegistry.DIAMOND_SICKLE,
                WeaponsRegistry.DRAGON_BONE_SICKLE,
                WeaponsRegistry.ELVEN_STEEL_SICKLE,
                WeaponsRegistry.GOLDEN_SICKLE,
                WeaponsRegistry.INFERNAL_IRON_SICKLE,
                WeaponsRegistry.IRON_SICKLE,
                WeaponsRegistry.MITHRIL_SICKLE,
                WeaponsRegistry.NETHERITE_SICKLE,
                WeaponsRegistry.PALLADIUM_SICKLE,
                WeaponsRegistry.PLATINUM_SICKLE,
                WeaponsRegistry.SHADOW_ADAMANTINE_DRAGON_BONE_SICKLE,
                WeaponsRegistry.SHADOW_ADAMANTINE_SICKLE,
                WeaponsRegistry.SILVER_SICKLE,
                WeaponsRegistry.STEEL_SICKLE,
                WeaponsRegistry.STONE_SICKLE,
                WeaponsRegistry.TUNGSTEN_CARBIDE_SICKLE,
                WeaponsRegistry.WOODEN_SICKLE
        );
        getOrCreateTagBuilder(TagKey.of(RegistryKeys.ITEM, new Identifier("c", "tridents"))).add(
                // WeaponsRegistry.ADAMANTINE_DRAGON_BONE_TRIDENT,
                WeaponsRegistry.ADAMANTINE_TRIDENT,
                WeaponsRegistry.BONE_TRIDENT,
                WeaponsRegistry.BRONZE_TRIDENT,
                WeaponsRegistry.COLD_IRON_TRIDENT,
                WeaponsRegistry.COPPER_TRIDENT,
                WeaponsRegistry.DARK_STEEL_TRIDENT,
                WeaponsRegistry.DIAMOND_TRIDENT,
                WeaponsRegistry.DRAGON_BONE_TRIDENT,
                WeaponsRegistry.ELVEN_STEEL_TRIDENT,
                WeaponsRegistry.GOLDEN_TRIDENT,
                WeaponsRegistry.INFERNAL_IRON_TRIDENT,
                WeaponsRegistry.IRON_TRIDENT,
                WeaponsRegistry.MITHRIL_TRIDENT,
                WeaponsRegistry.NETHERITE_TRIDENT,
                WeaponsRegistry.PALLADIUM_TRIDENT,
                WeaponsRegistry.PLATINUM_TRIDENT,
                // WeaponsRegistry.SHADOW_ADAMANTINE_DRAGON_BONE_TRIDENT,
                WeaponsRegistry.SHADOW_ADAMANTINE_TRIDENT,
                WeaponsRegistry.SILVER_TRIDENT,
                WeaponsRegistry.STEEL_TRIDENT,
                WeaponsRegistry.STONE_TRIDENT,
                WeaponsRegistry.TUNGSTEN_CARBIDE_TRIDENT,
                WeaponsRegistry.WOODEN_TRIDENT
        );
        getOrCreateTagBuilder(TagKey.of(RegistryKeys.ITEM, new Identifier("c", "warhammers"))).add(
                WeaponsRegistry.ADAMANTINE_DRAGON_BONE_WARHAMMER,
                WeaponsRegistry.ADAMANTINE_WARHAMMER,
                WeaponsRegistry.BONE_WARHAMMER,
                WeaponsRegistry.BRONZE_WARHAMMER,
                WeaponsRegistry.COLD_IRON_WARHAMMER,
                WeaponsRegistry.COPPER_WARHAMMER,
                WeaponsRegistry.DARK_STEEL_WARHAMMER,
                WeaponsRegistry.DIAMOND_WARHAMMER,
                WeaponsRegistry.DRAGON_BONE_WARHAMMER,
                WeaponsRegistry.ELVEN_STEEL_WARHAMMER,
                WeaponsRegistry.GOLDEN_WARHAMMER,
                WeaponsRegistry.INFERNAL_IRON_WARHAMMER,
                WeaponsRegistry.IRON_WARHAMMER,
                WeaponsRegistry.MITHRIL_WARHAMMER,
                WeaponsRegistry.NETHERITE_WARHAMMER,
                WeaponsRegistry.PALLADIUM_WARHAMMER,
                WeaponsRegistry.PLATINUM_WARHAMMER,
                WeaponsRegistry.SHADOW_ADAMANTINE_DRAGON_BONE_WARHAMMER,
                WeaponsRegistry.SHADOW_ADAMANTINE_WARHAMMER,
                WeaponsRegistry.SILVER_WARHAMMER,
                WeaponsRegistry.STEEL_WARHAMMER,
                WeaponsRegistry.STONE_WARHAMMER,
                WeaponsRegistry.TUNGSTEN_CARBIDE_WARHAMMER,
                WeaponsRegistry.WOODEN_WARHAMMER
        );
    }
}
